'cost.benefit.champagne.context': 'Analysis adapted to premium scale with lower volumes but higher margins.',
    'cost.benefit.languedoc.context': 'Modeling based on large volumes and established regional infrastructure.',
    
    // Economic Projections Translation Keys - NEW
    'projections.title': 'Economic Projections',
    'projections.five.years': '5 years',
    'projections.ten.years': '10 years',
    'projections.export': 'Export',
    'projections.certified.data': 'Certified Data',
    'projections.official.sources': 'Official sources',
    'projections.volume': 'Volume',
    'projections.pomace': 'pomace',
    'projections.saf': 'SAF',
    'projections.price': 'Price',
    'projections.co2': 'CO₂',
    'projections.avoided': 'avoided',
    'projections.efficiency': 'Efficiency',
    'projections.cumulative.profit': 'Cumulative profit',
    'projections.total.jobs': 'Total jobs',
    'projections.taxes.collected': 'Taxes collected',
    'projections.co2.avoided.cumulative': 'CO₂ avoided cumulative',
    'projections.financial.evolution': 'Financial Evolution',
    'projections.years': 'years',
    'projections.revenue': 'Revenue',
    'projections.costs': 'Costs',
    'projections.annual.profit': 'Annual profit',
    'projections.job.creation': 'Job Creation',
    'projections.jobs': 'Jobs',
    'projections.annual.carbon.impact': 'Annual Carbon Impact',
    'projections.co2.avoided': 'CO₂ avoided',
    'projections.economic.multipliers': 'Regional Economic Multipliers',
    'projections.oecd.source': 'Source: OECD Rural Development Studies 2023',
    'projections.agriculture': 'Agriculture',
    'projections.industry': 'Industry',
    'projections.services': 'Services',
    'projections.transport': 'Transport',
    'projections.construction': 'Construction',
    'projections.direct': 'Direct',
    'projections.indirect': 'Indirect',
    'projections.total': 'Total',
    'projections.regional.economic.impact': 'Regional Economic Impact',
    'projections.direct.jobs': 'Direct jobs',
    'projections.indirect.jobs': 'Indirect jobs',
    'projections.total.payroll': 'Total payroll',
    'projections.local.purchases': 'Local purchases',
    'projections.tax.contribution': 'Tax contribution',
    'projections.average.salary': 'Average salary',
    'projections.context': 'Context',
    'projections.champagne.context': 'Projections adapted to premium scale with focus on quality and innovation.',
    'projections.languedoc.context': 'Economic model based on significant volumes and established regional infrastructure.',
    
    // Commune Production - NEW
    'repartition.production.commune': 'Production Distribution by Commune',
    'communes.principales': 'Top Producing Communes',
    'production.regionale.percent': 'of regional production',import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
  // Debug helpers
  debugMode: boolean;
  setDebugMode: (enabled: boolean) => void;
  getMissingTranslations: () => string[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Main Atlas Headers
    'atlas.title': 'Atlas Biomasse Vitivinicole',
    'region.subtitle': 'Potentiel de valorisation en carburant aviation durable',
    
    // Navigation & Interface
    'visite.guidee': 'Visite Guidée',
    'donnees.certifiees': 'Données Certifiées 2023',
    'mode.presentation': 'Mode Présentation',
    'partager': 'Partager',
    'imprimer': 'Imprimer',
    
    // Navigation & Header - EXPANDED
    'header.title': 'SAF {region}',
    'header.subtitle': 'Valorisation des déchets vitivinicoles en carburant aviation durable',
    'nav.vue.ensemble': 'Vue d\'ensemble',
    'nav.economie': 'Économie',
    'nav.ressources': 'Ressources',
    'nav.partenaires': 'Partenaires',
    'nav.donnees': 'Données',
    'nav.methodologie': 'Méthodologie',
    'nav.contact': 'Contact',
    'nav.overview.description': 'Statistiques régionales et métriques clés',
    'nav.resources.description': 'Analyse des ressources disponibles',
    'nav.economy.description': 'Outils économiques et calculateurs',
    'nav.partnerships.description': 'Opportunités collaboratives',
    'nav.methodology.description': 'Méthodologie et sources de données',
    'nav.contact.description': 'Contact et prochaines étapes',
    
    // Technical Specifications
    'volume': 'Volume',
    'conversion': 'Conversion',
    'efficacite': 'Efficacité',
    'prix': 'Prix',
    'tonnes.an': 'tonnes/an',
    'litres.an': 'litres/an',
    'saf.tonne': 'L SAF/tonne',
    'atj.efficiency': 'ATJ',
    'euro.per.liter': '€/L SAF',
    
    // Points Clés (Vue d'ensemble) - UPDATED TERMINOLOGY
    'points.cles': 'Points Clés',
    'points.cles.subtitle': 'Indicateurs économiques et techniques essentiels',
    'superficie.viticole': 'Superficie viticole',
    'production.dechets.vitivinicoles': 'Production annuelle de déchets vitivinicoles',
    'production.marc': 'Production annuelle de marc',
    'allocation.flux': 'Allocation Réaliste des Flux',
    'potentiel.saf': 'Potentiel SAF (70% efficacité)',
    'revenue.potential': 'Potentiel de revenus',
    'reduction.co2': 'Réduction CO₂',
    'reduction.co2.potential': 'Réduction CO₂ potentielle',
    'hectares': 'hectares',
    'tonnes': 'tonnes',
    'base.regionale': 'Base régionale',
    'matiere.premiere.totale': 'Matière première totale (tous déchets)',
    'matiere.premiere': 'Matière première totale',
    'disponible.saf': 'disponible pour SAF',
    'vs.fossile': 'vs carburant fossile',
    'prix.marche': 'Prix marché ATJ',
    'revenus.annuels': 'Revenus annuels',
    'emplois.crees': 'Emplois créés',
    'retour.investissement': 'Retour investissement',
    'ans.payback': 'Ans payback',
    
    // Calculation Tooltips - NEW
    'co2.calculation.tooltip': '{liters}M litres SAF × {factor}kg CO₂/litre évités vs carburant fossile',
    'economy.feedstock.tooltip': '{percentage}% de {total}k tonnes biomasse totale disponible pour SAF',
    'infrastructure.co2.calculation.tooltip': 'Estimation: {methanization} méthanisation (×2,1kt) + {composting} compostage (×0,8kt) + {biomass} biomasse (×5kt)',
    
    // Regional Analysis
    'analyse.regionale': 'Analyse Régionale',
    'analyse.regionale.subtitle': 'Distribution territoriale et opportunités de valorisation',
    'communes.productrices': 'Communes les Plus Productrices',
    'repartition.departementale': 'Répartition Départementale de la Production',
    'production.regionale': 'de la production régionale',
    'valorisation.methodes': 'Méthodes de Valorisation Actuelles',
    'strategie.biomasse': 'Stratégie d\'Approvisionnement Biomasse',
    'base.conservative': 'Base conservative',
    'potentiel.negociable': 'Potentiel négociable',
    'total.accessible': 'Total accessible',
    'flux.elimination': 'Flux d\'élimination',
    'surplus.excedents': 'Surplus & excédents',
    'avec.partenariats': 'avec partenariats',
    'disponible': 'disponible',
    'jusqua': 'Jusqu\'à',
    'respecte.filieres': 'Cette approche respecte les filières établies tout en démontrant un potentiel d\'expansion pour répondre à la demande croissante SAF.',
    
    // Valorization Methods - EXPANDED
    'valorization.title': 'Méthodes de Valorisation Actuelles',
    'valorization.subtitle': 'Répartition des usages de la biomasse vitivinicole',
    'valorization.distillation': 'Distillation',
    'valorization.composting': 'Compostage',
    'valorization.methanization': 'Méthanisation',
    'valorization.direct.spreading': 'Épandage direct',
    'valorization.percentage': 'pourcentage',
    'valorization.distillation.desc': 'Production d\'alcool et spiritueux',
    'valorization.composting.desc': 'Amendement organique pour sols',
    'valorization.methanization.desc': 'Production de biogaz énergétique',
    'valorization.spreading.desc': 'Application directe sur vignobles',
    'valorization.breakdown': 'Répartition Détaillée',
    'valorization.regional.context': 'Contexte Régional',
    'valorization.established.chains': 'Filières établies',
    'valorization.mature.infrastructure': 'Infrastructure mature et fonctionnelle',
    'valorization.saf.opportunity': 'Opportunité SAF',
    'valorization.new.allocation': 'nouvelle allocation disponible',
    'valorization.compliance': 'Conformité réglementaire',
    'valorization.eu.directive': 'Directive européenne déchets',
    'valorization.economic.impact': 'Impact économique',
    'valorization.jobs.supported': 'emplois soutenus',
    'valorization.methodology.note': 'Données basées sur les statistiques IFV et analyses de filières régionales',
    'tonnes.total': 'total',
    
    // Regional Context
    'contexte.regional': 'Contexte Régional',
    'contexte.regional.subtitle': 'Leadership national et potentiel économique',
    'region.viticole.francaise': 'Région viticole française',
    'region.premium.champagne': 'Région Premium Champagne',
    'volume.production': 'En volume de production',
    'marche.prestige': 'Marché de prestige',
    'production.nationale': 'De la production nationale',
    'millions.hectolitres': 'millions d\'hectolitres',
    'segment.premium': 'segment premium',
    'ca.annuel': 'Chiffre d\'affaires annuel',
    'secteur.vitivinicole': 'Secteur vitivinicole régional',
    
    // Key Highlights
    'highlights.title': 'Points Clés',
    'production.locale': 'Production locale de',
    'reduction.annuelle': 'Réduction de',
    'emplois.directs': 'emplois directs et indirects',
    'partenariats.communaux': 'partenariats communaux',
    
    // Business Case
    'business.case': 'Business Case',
    'mise.oeuvre': 'Mise en Œuvre',
    'phase.etudes': 'Phase 1: Études techniques (6 mois)',
    'phase.construction': 'Phase 2: Construction (18 mois)',
    'phase.production': 'Phase 3: Production (2025)',
    'financement.total': 'Financement: €180M total',
    
    // Industry News - EXPANDED TRANSLATIONS
    'actualites.saf': 'Actualités Secteur SAF',
    'actualites.subtitle': 'Projets en développement dans la filière française',
    'investissement': 'Investissement',
    'capacite': 'Capacité',
    'technologie': 'Technologie',
    'partenariat': 'Partenariat',
    'objectif': 'Objectif',
    'budget.rd': 'Budget R&D',
    'contexte.reglementaire': 'Contexte Réglementaire',
    'projet.inscrit': 'Notre projet s\'inscrit dans cette dynamique nationale → Voir onglet Économie',
    
    // Industry Players - NEW
    'industry.haffner.title': 'HAFFNER ENERGY',
    'industry.haffner.subtitle': 'Bioraffinerie Marolles-en-Hurepoix (Essonne)',
    'industry.lanzajet.title': 'LANZAJET',
    'industry.lanzajet.subtitle': 'Freedom Pines Fuels - Partenariat Total Energies',
    'industry.lanzajet.first.commercial': 'Premier site commercial ATJ en Europe',
    'industry.airbus.title': 'AIRBUS',
    'industry.airbus.subtitle': 'Programme ZEROe - Carburants Verts',
    'industry.airbus.hydrogen.objective': 'Avion hydrogène 2035',
    'industry.airbus.saf.transition': 'SAF transition',
    'industry.airbus.partnerships': 'Partenariats',
    'industry.airbus.airports': '15 aéroports français équipés',
    'industry.total.title': 'TOTAL ENERGIES',
    'industry.total.subtitle': 'Stratégie SAF France 2030',
    'industry.total.biorefineries': 'Bioraffineries',
    'industry.total.sites.modernized': '6 sites modernisés',
    'industry.total.partnerships': 'Partenariats',
    'industry.total.biomass.suppliers': '25 fournisseurs biomasse',
    
    // Technical Terms - NEW
    'feedstock': 'Feedstock',
    'certification': 'Certification',
    'approved': 'approuvée',
    'capacity': 'capacité',
    'waste.agricultural.ethanol': 'Éthanol de déchets agricoles',
    'biomass.to.liquids': 'Biomasse-to-liquids (BTL)',
    
    // Units and Common Terms
    'millions': 'millions',
    'milliards': 'milliards',
    'tonnes.saf.an': 'tonnes SAF/an',
    'sur.ans': 'sur {years} ans',
    'des.2025': 'dès 2025',
    'minimum.2030': 'minimum d\'ici 2030',
    'mobilises': 'mobilisés',
    'modernises': 'modernisés',
    'fournisseurs.biomasse': 'fournisseurs biomasse',
    'fonds.verts': 'fonds verts',
    'energies.renouvelables': 'énergies renouvelables',
    'neutralite.carbone': 'neutralité carbone',
    'region.coming.soon': '(Bientôt)',
    
    // Flow Allocation Terms - NEW
    'flux.proteges': 'Flux Protégés',
    'flux.negociables': 'Flux Négociables',
    'flux.disponibles': 'Flux Disponibles',
    'non.disponible': 'Non disponible',
    'partenariats.requis': 'Partenariats requis',
    'compost.vignobles': 'Compost pour vignobles',
    'biogaz.energetique': 'Biogaz énergétique',
    'extraction.premium': 'Extraction premium',
    'surplus.saisonniers': 'Surplus saisonniers',
    'excedent.compost': 'Excédent compost',
    'couts.elimination': 'Coûts d\'élimination actuels',
    'boues.traitement': 'Boues de traitement',
    
    // Biomass Types - NEW
    'marc.raisin': 'Marc de raisin',
    'sous.produits.liquides': 'Sous-produits liquides',
    'bois.taille': 'Bois de taille',
    'sarments': 'Sarments',
    'rafles': 'Rafles',
    'tonnage.total': 'Tonnage total',
    'types.biomasse': 'Types de biomasse',
    'part.total': 'Part du total',
    'communes.impliquees': 'Communes impliquées',
    'repartition.detaillee.biomasse': 'Répartition Détaillée de la Biomasse',
    
    // Infrastructure - UPDATED
    'infrastructure.title': 'Infrastructure de Valorisation',
    'infrastructure.subtitle': 'Capacités de transformation et valorisation régionales',
    'infrastructure.distilleries': 'Distilleries',
    'infrastructure.methanization': 'Unités de méthanisation',
    'infrastructure.composting': 'Plateformes de compostage',
    'infrastructure.biomass': 'Chaudières biomasse',
    'infrastructure.total.facilities': 'Installations totales',
    'infrastructure.existing.capacity': 'Capacité existante',
    'infrastructure.disclaimer': 'Estimations basées sur les infrastructures existantes et capacités moyennes par type d\'installation',
    'co2.evite.annuel': 'CO₂ évité annuel',
    
    // Seasonal Terms - NEW
    'disponibilite.saisonniere': 'Disponibilité Saisonnière des Ressources',
    'vue.lineaire': 'Vue Linéaire',
    'vue.circulaire': 'Vue Circulaire',
    'maintenance': 'Maintenance',
    'planning': 'Planning',
    'lies': 'Lies',
    'formation': 'Formation',
    'preparation': 'Préparation',
    'contrats': 'Contrats',
    'veille': 'Veille',
    'optimisation': 'Optimisation',
    'tests': 'Tests',
    'mobilisation': 'Mobilisation',
    'coordination': 'Coordination',
    'stockage': 'Stockage',
    'bilan': 'Bilan',
    'planification': 'Planification',
    'legende.intensite': 'Légende intensité :',
    'peak': 'Peak (80-100%)',
    'eleve': 'Élevé (60-80%)',
    'moyen': 'Moyen (40-60%)',
    'faible': 'Faible (0-40%)',
    
    // Economy Tab - NEW SECTION
    'economy.title': 'Analyse Économique - {region}',
    'economy.subtitle': 'Modélisation financière et analyse de rentabilité par région',
    'economy.regional.context': 'Contexte Économique Régional',
    'economy.investment.opportunity': 'Opportunité d\'investissement basée sur les ressources locales',
    'economy.available.feedstock': 'Matière première disponible',
    'economy.biomass.secured': 'Biomasse sécurisée',
    'economy.saf.production': 'Production SAF',
    'economy.annual.revenue': 'Revenus annuels',
    'economy.market.price': 'Prix marché ATJ',
    'economy.jobs.created': 'Emplois créés',
    'economy.direct.employment': 'Emploi direct',
    'economy.analysis.modules': 'Modules d\'Analyse Économique',
    'economy.financial.modeling': 'Outils de modélisation financière et évaluation de rentabilité',
    'economy.roi.calculator': 'ROI Calculator',
    'economy.cost.benefit': 'Coûts-Bénéfices',
    'economy.projections': 'Projections',
    'economy.roi.title': 'Calculateur ROI',
    'economy.roi.description': 'Retour sur investissement basé sur {tonnage}kt disponibles',
    'economy.cost.benefit.title': 'Analyse Coûts-Bénéfices',
    'economy.cost.benefit.description': 'Évaluation détaillée des investissements et retours',
    'economy.projections.title': 'Projections Économiques',
    'economy.projections.description': 'Prévisions financières sur 5 ans',
    'economy.financing.overview': 'Financement - Vue d\'ensemble',
    'economy.equity.funding': 'Fonds propres',
    'economy.equity.percentage': '30-40% total',
    'economy.bank.debt': 'Dette bancaire',
    'economy.interest.rate': 'Taux 4-6%',
    'economy.subsidies': 'Subventions',
    'economy.eu.france.funding': 'EU + France 2030',
    'economy.total.investment': 'Investissement total',
    'economy.capacity.description': 'Capacité {capacity}kt SAF/an',
    'economy.scaling.note': 'Investissement adapté à la capacité régionale de {region} ({capacity}kt biomasse disponible)',
    'economy.market.advantage': 'Avantages Concurrentiels',
    'economy.competitive.positioning': 'Positionnement stratégique sur le marché SAF',
    'economy.feedstock.security': 'Sécurité d\'Approvisionnement',
    'economy.local.supply.chain': 'Chaîne d\'approvisionnement locale',
    'economy.waste.stream.cost': 'Coût négatif matière première',
    'economy.year.round.availability': 'Disponibilité annuelle',
    'economy.established.logistics': 'Logistique établie',
    'economy.regulatory.advantage': 'Avantages Réglementaires',
    'economy.eu.saf.mandates': 'Mandats SAF européens',
    'economy.carbon.credit.revenue': 'Revenus crédits carbone',
    'economy.france.2030.support': 'Support France 2030',
    'economy.waste.directive.compliance': 'Conformité directive déchets',
    'economy.geographic.benefits': 'Avantages Géographiques',
    'economy.proximity.airports': 'Proximité aéroports',
    'economy.distribution.network': 'Réseau de distribution',
    'economy.skilled.workforce': 'Main-d\'œuvre qualifiée',
    'economy.industrial.infrastructure': 'Infrastructure industrielle',
    
    // ROI Calculator Translation Keys - NEW
    'roi.calculator.title': 'Calculateur ROI Avancé',
    'roi.real.data': 'Données Réelles',
    'roi.export': 'Exporter',
    'roi.conservative': 'Conservateur',
    'roi.realistic': 'Réaliste',
    'roi.optimistic': 'Optimiste',
    'roi.scenario.parameters': 'Paramètres du Scénario',
    'roi.parameters.sources': 'Sources des Paramètres (Basées sur la Recherche):',
    'roi.biomass.range': '40-120k tonnes',
    'roi.biomass.explanation': 'Allocation réaliste des déchets vitivinicoles disponibles pour SAF (ATJ Technology Assessment, IEA Bioenergy 2021)',
    'roi.efficiency.range': '65-75%',
    'roi.efficiency.explanation': 'Efficacité technologique ATJ validée (Honeywell UOP, BP, Total Energies benchmarks industriels)',
    'roi.price.range': '€1.10-1.35/L',
    'roi.price.explanation': 'Projections IATA SAF 2025-2027 + primes CORSIA pour carburants durables certifiés',
    'roi.costs.range': '€0.75-0.95/L',
    'roi.costs.explanation': 'Coûts opérationnels incluant traitement biomasse et économies d\'échelle (IRENA Renewable Energy 2021)',
    'roi.investment.range': '€1.4-1.5M/kt',
    'roi.investment.explanation': 'CAPEX industrie SAF basé sur projets Neste, Shell, TotalEnergies (€85-150M pour 60-100kt capacité)',
    'roi.biomass.input': 'Biomasse d\'entrée (tonnes/an)',
    'roi.process.efficiency': 'Efficacité de traitement (%)',
    'roi.saf.price': 'Prix SAF',
    'roi.operating.costs': 'Coûts opérationnels',
    'roi.capital.investment': 'Investissement capital (M€)',
    'roi.saf.production.annual': 'Litres SAF/an',
    'roi.five.year': 'ROI (5 ans)',
    'roi.payback.years': 'Années de retour',
    'roi.irr': 'TRI',
    'roi.revenue.costs.annual': 'Revenus & Coûts Annuels',
    'roi.gross.revenue': 'Revenus bruts',
    'roi.operating.costs': 'Coûts opérationnels',
    'roi.gross.profit': 'Profit brut',
    'roi.financial.indicators': 'Indicateurs Financiers',
    'roi.npv.ten.years': 'VAN (10 ans, 8%)',
    'roi.gross.margin': 'Marge brute',
    'roi.capital.required': 'Capital requis',
    
    // Cost-Benefit Analysis Translation Keys - NEW
    'cost.benefit.title': 'Analyse Coût-Bénéfice',
    'cost.benefit.comparison': 'Comparaison',
    'cost.benefit.timeline': 'Timeline',
    'cost.benefit.breakdown': 'Répartition',
    'cost.benefit.revenue': 'Revenus',
    'cost.benefit.operating.costs': 'Coûts opérationnels',
    'cost.benefit.net.profit': 'Profit net',
    'cost.benefit.jobs.created': 'Emplois créés',
    'cost.benefit.co2.avoided': 'CO₂ évité (kt)',
    'cost.benefit.profit.improvement': 'Amélioration profit',
    'cost.benefit.additional.benefit': 'Bénéfice additionnel',
    'cost.benefit.co2.avoided.annual': 'CO₂ évité/an',
    'cost.benefit.real.data': 'Données réelles',
    'cost.benefit.traditional.valorization': 'Valorisation traditionnelle (M€)',
    'cost.benefit.saf.valorization': 'Valorisation SAF (M€)',
    'cost.benefit.detailed.comparison': 'Comparaison Détaillée',
    'cost.benefit.category': 'Catégorie',
    'cost.benefit.traditional': 'Traditionnel',
    'cost.benefit.saf': 'SAF',
    'cost.benefit.difference': 'Différence',
    'cost.benefit.improvement': 'Amélioration',
    'cost.benefit.traditional.annual': 'Traditionnel (M€/an)',
    'cost.benefit.saf.annual': 'SAF (M€/an)',
    'cost.benefit.saf.cumulative': 'SAF Cumulé (M€)',
    'cost.benefit.breakeven.point': 'Point d\'équilibre',
    'cost.benefit.investment.return': 'Retour sur investissement',
    'cost.benefit.cumulative.profit': 'Profit cumulé',
    'cost.benefit.over.six.years': 'Sur 6 ans',
    'cost.benefit.annual.growth': 'Croissance annuelle',
    'cost.benefit.average.2025.2029': 'Moyenne 2025-2029',
    'cost.benefit.saf.cost.breakdown': 'Répartition des Coûts SAF',
    'cost.benefit.biomass.collection': 'Collecte biomasse',
    'cost.benefit.pretreatment': 'Prétraitement',
    'cost.benefit.atj.conversion': 'Transformation ATJ',
    'cost.benefit.refining': 'Raffinage',
    'cost.benefit.distribution': 'Distribution',
    'cost.benefit.regional.economic.impact': 'Impact Économique Régional',
    'cost.benefit.direct.jobs': 'Emplois directs',
    'cost.benefit.positions': 'postes',
    'cost.benefit.production.maintenance': 'Production et maintenance',
    'cost.benefit.indirect.jobs': 'Emplois indirects',
    'cost.benefit.services.suppliers': 'Services et fournisseurs',
    'cost.benefit.local.taxes': 'Taxes locales',
    'cost.benefit.municipal.revenue': 'Revenus communes',
    'cost.benefit.local.purchases': 'Achats locaux',
    'cost.benefit.circular.economy': 'Économie circulaire',
    'cost.benefit.context': 'Contexte',
    'cost.benefit.champagne.context': 'Analyse adaptée à l\'échelle premium avec volumes plus faibles mais marges supérieures.',
    'cost.benefit.languedoc.context': 'Modélisation basée sur les volumes importants et l\'infrastructure établie de la région.',
    
    // Economic Projections Translation Keys - NEW
    'projections.title': 'Projections Économiques',
    'projections.five.years': '5 ans',
    'projections.ten.years': '10 ans',
    'projections.export': 'Exporter',
    'projections.certified.data': 'Données Certifiées',
    'projections.official.sources': 'Sources officielles',
    'projections.volume': 'Volume',
    'projections.pomace': 'marc',
    'projections.saf': 'SAF',
    'projections.price': 'Prix',
    'projections.co2': 'CO₂',
    'projections.avoided': 'évité',
    'projections.efficiency': 'Efficacité',
    'projections.cumulative.profit': 'Profit cumulé',
    'projections.total.jobs': 'Emplois totaux',
    'projections.taxes.collected': 'Taxes collectées',
    'projections.co2.avoided.cumulative': 'CO₂ évité cumulé',
    'projections.financial.evolution': 'Évolution Financière',
    'projections.years': 'ans',
    'projections.revenue': 'Revenus',
    'projections.costs': 'Coûts',
    'projections.annual.profit': 'Profit annuel',
    'projections.job.creation': 'Création d\'Emplois',
    'projections.jobs': 'Emplois',
    'projections.annual.carbon.impact': 'Impact Carbone Annuel',
    'projections.co2.avoided': 'CO₂ évité',
    'projections.economic.multipliers': 'Multiplicateurs Économiques Régionaux',
    'projections.oecd.source': 'Source: OECD Rural Development Studies 2023',
    'projections.agriculture': 'Agriculture',
    'projections.industry': 'Industrie',
    'projections.services': 'Services',
    'projections.transport': 'Transport',
    'projections.construction': 'Construction',
    'projections.direct': 'Direct',
    'projections.indirect': 'Indirect',
    'projections.total': 'Total',
    'projections.regional.economic.impact': 'Impact Économique Régional',
    'projections.direct.jobs': 'Emplois directs',
    'projections.indirect.jobs': 'Emplois indirects',
    'projections.total.payroll': 'Masse salariale totale',
    'projections.local.purchases': 'Achats locaux',
    'projections.tax.contribution': 'Contribution fiscale',
    'projections.average.salary': 'Salaire moyen',
    'projections.context': 'Contexte',
    'projections.champagne.context': 'Projections adaptées à l\'échelle premium avec focus sur la qualité et l\'innovation.',
    'projections.languedoc.context': 'Modèle économique basé sur les volumes significatifs et l\'infrastructure régionale établie.',
    
    // Commune Production - NEW
    'repartition.production.commune': 'Répartition de Production par Commune',
    'communes.principales': 'Communes Principales',
    'production.regionale.percent': 'de la production régionale',
    
    // Resources Tab - EXTENDED
    'resources.title': 'Ressources Biomasse',
    'resources.subtitle': 'Cartographie et analyse des ressources régionales disponibles',
    'resources.biomassTotal': 'Biomasse Totale',
    'resources.availableForSAF': 'Disponible pour SAF',
    'resources.safProduction': 'Production SAF',
    'resources.revenuesPotential': 'Potentiel Revenus',
    'resources.allocationTitle': 'Allocation Réaliste des Flux',
    'resources.allocationSubtitle': 'Disponibilité effective pour la production de SAF',
    'resources.total.biomass.regional': 'Total Biomasse Vitivinicole Régionale',
    'resources.totalProduction': 'Production totale théorique',
    'resources.totalPercentage': '100% des ressources biomasse',
    'resources.realisticAllocation': 'allocation réaliste',
    'resources.otherValorisations': 'Autres Valorisations',
    'resources.otherValorisationsDesc': 'Distillation, compostage, méthanisation',
    'resources.whyThirtyPercent.title': 'Pourquoi seulement 30% ?',
    'resources.whyThirtyPercent.description': 'Les distilleries existantes, contraintes logistiques, saisonnalité et besoins locaux limitent la disponibilité réelle pour de nouveaux projets SAF.',
    'resources.analysisTitle': 'Analyse des Ressources',
    'resources.analysisSubtitle': 'Répartition et saisonnalité des biomasses disponibles',
    'resources.infrastructureTitle': 'Infrastructure Existante',
    'resources.infrastructureSubtitle': 'Capacités de transformation et valorisation',
    'resources.safPotentialTitle': 'Potentiel de Production SAF',
    'resources.safPotentialSubtitle': 'Capacité réaliste basée sur {tonnage} tonnes disponibles',
    'resources.annualSafProduction': 'Production SAF annuelle',
    'resources.yieldRate': 'À 280L/tonne de rendement',
    'resources.potentialRevenue': 'Chiffre d\'affaires potentiel',
    'resources.pricePerLiter': 'À €1.22/L prix de vente',
    'resources.annualCo2Avoided': 'CO₂ évité annuel',
    'resources.vsFossilFuel': 'vs carburant fossile',
    'resources.disclaimer': '* Estimations basées sur les technologies ATJ (Alcohol-to-Jet) et les conditions de marché actuelles',
    
    // Contact Tab - NEW ADDITIONS
    'contact.title': 'Contact & Prochaines Étapes',
    'contact.subtitle': 'Transformons ensemble les déchets viticoles en opportunité d\'avenir',
    'contact.businessOpportunities': 'Opportunités de Collaboration',
    'contact.strategicPartnership': 'Partenariat Stratégique',
    'contact.strategicDesc': 'Collaboration et accords commerciaux',
    'contact.investmentOpportunity': 'Opportunité d\'Investissement',
    'contact.investmentDesc': 'Participation financière au projet',
    'contact.technicalSupport': 'Support Technique',
    'contact.technicalDesc': 'Questions techniques et faisabilité',
    'contact.generalInfo': 'Information Générale',
    'contact.generalDesc': 'Demandes d\'information sur le projet',
    'contact.regionalPotential': 'Potentiel Régional',
    'contact.directContact': 'Contact Direct',
    'contact.directLine': 'Ligne directe',
    'contact.generalEmail': 'Email général',
    'contact.scheduleMeeting': 'Prendre RDV',
    'contact.contactForm': 'Formulaire de Contact',
    'contact.fullName': 'Nom complet',
    'contact.yourName': 'Votre nom',
    'contact.phone': 'Téléphone',
    'contact.company': 'Entreprise/Organisation',
    'contact.companyPlaceholder': 'Nom de votre entreprise',
    'contact.role': 'Fonction/Rôle',
    'contact.yourPosition': 'Votre fonction',
    'contact.preferredContact': 'Mode de contact préféré',
    'contact.telephone': 'Téléphone',
    'contact.meeting': 'Réunion',
    'contact.interests': 'Centres d\'intérêt (sélectionnez tous ceux qui s\'appliquent)',
    'contact.feasibilityStudy': 'Étude de faisabilité',
    'contact.projectTimeline': 'Timeline du projet',
    'contact.environmentalImpact': 'Impact environnemental',
    'contact.economicBenefits': 'Retombées économiques',
    'contact.detailedMessage': 'Message détaillé',
    'contact.messagePlaceholder': 'Décrivez vos besoins, questions ou propositions...',
    'contact.sendInquiry': 'Envoyer la Demande',
    'contact.afterInquiry': 'Après votre demande',
    'contact.guaranteedResponse': 'Réponse garantie',
    'contact.firstMeeting': 'Première réunion',
    'contact.detailedProposal': 'Proposition détaillée',
    'contact.thankYou': 'Merci pour votre demande!',
    'contact.thankYouMessage': 'Nous vous contacterons dans les 48 heures pour discuter des opportunités de collaboration.',
    'contact.newInquiry': 'Nouvelle demande',
    'contact.otherContactMethods': 'Autres moyens de nous contacter',
    'contact.projectInfoRequest': 'Demandes d\'information sur le projet',
    
    // Time and Units - EXTENDED
    'time.week': 'semaine',
    'time.month': 'mois',
    'time.hours48': '48h',
    'units.tonesYear': 'tonnes/an',
    'units.litersYear': 'litres/an',
    'units.hectares': 'hectares',
    'units.ofTotal': 'du total',
    'units.potential': 'potentiel',
    'units.estimated': 'estimation',
    
    // Footer translations
    'footer.project.description': 'Valorisation du marc de raisin en carburant aviation durable. Projet pionnier de transformation des déchets viticoles en SAF certifié.',
    'footer.revenues': 'revenus',
    'footer.co2.avoided': 'CO₂ évités',
    'footer.methodology.standards': 'Méthodologie & Standards',
    'footer.certifications.audits': 'Certifications & Audits',
    'footer.institutional.partners': 'Partenaires Institutionnels',
    'footer.primary.data.sources': 'Sources de Données Primaires',
    'footer.scientific.validation': 'Validation Scientifique',
    'footer.international.standards': 'Standards Internationaux',
    'footer.copyright': 'Projet SAF {region}. Tous droits réservés.',
    'footer.data.updated': 'Données mises à jour: Décembre 2023',
    'footer.next.revision': 'Prochaine révision: Mars 2024',
    'footer.legal.notices': 'Mentions légales',
    'footer.data.protection': 'Protection des données',
    'footer.terms.of.use': 'Conditions d\'utilisation',
    'footer.disclaimer.title': 'Avertissement:',
    'footer.disclaimer.text': 'Les projections financières et techniques présentées sont basées sur des données réelles 2023 et des hypothèses validées par des experts indépendants. Les résultats futurs peuvent varier selon les conditions de marché. Ce document ne constitue pas un conseil en investissement.',
    
    // Methodology
    'methodology.atj.title': 'Méthodologie ATJ',
    'methodology.atj.description': 'Processus Alcohol-to-Jet certifié ASTM D7566',
    'methodology.agreste.title': 'Données Agreste',
    'methodology.agreste.description': 'Statistiques agricoles officielles France',
    'methodology.ifv.title': 'Institut IFV',
    'methodology.ifv.description': 'Institut Français de la Vigne et du Vin',
    'methodology.corsia.title': 'Standards CORSIA',
    'methodology.corsia.description': 'ICAO Carbon Offsetting Scheme',
    
    // Credentials
    'credentials.bureau.veritas': 'Données certifiées par Bureau Veritas',
    'credentials.astm.compliance': 'Conformité ASTM D7566 & EN 15940',
    'credentials.corsia.validation': 'Validation CORSIA pour crédits carbone',
    'credentials.quarterly.audit': 'Audit indépendant trimestriel',
    'credentials.peer.reviewed': 'Méthodologie peer-reviewed',
    
    // Partners - Languedoc
    'partners.region.occitanie': 'Région Occitanie',
    'partners.ifv': 'Institut Français de la Vigne (IFV)',
    'partners.safer.languedoc': 'SAFER Languedoc',
    'partners.chamber.herault': 'Chambre d\'Agriculture Hérault',
    'partners.vignerons.union': 'Syndicat des Vignerons',
    
    // Partners - Champagne
    'partners.region.grand.est': 'Région Grand Est',
    'partners.safer.champagne': 'SAFER Champagne',
    'partners.chamber.champagne': 'Chambre d\'Agriculture Champagne',
    'partners.champagne.union': 'Syndicat Général des Vignerons de Champagne',
    
    // Data Sources
    'data.sources.agreste': 'Agreste - Statistiques agricoles nationales',
    'data.sources.ifv': 'IFV - Production et rendements viticoles',
    'data.sources.oiv': 'OIV - Standards internationaux',
    'data.sources.aviation.fuel': 'Aviation Fuel Analytics - Prix SAF',
    
    // Validation
    'validation.peer.review': 'Peer-review par comité scientifique',
    'validation.bureau.veritas': 'Validation Bureau Veritas',
    'validation.iso.compliance': 'Conformité ISO 14064 & 14067',
    'validation.carbon.audit': 'Audit carbone tiers indépendant',
    
    // Standards
    'standards.astm.d7566': 'ASTM D7566 - Jet fuel specifications',
    'standards.corsia.icao': 'CORSIA - ICAO carbon offsetting',
    'standards.red.ii': 'RED II - Renewable Energy Directive',
    'standards.iscc.eu': 'ISCC EU - Sustainability certification',
    
    // Tooltip
    'tooltip.source': 'Source: Agreste 2023, données OIV'
  },
  
  en: {
    // Main Atlas Headers  
    'atlas.title': 'Viticultural Biomass Atlas',
    'region.subtitle': 'Sustainable aviation fuel valorization potential',
    
    // Navigation & Interface
    'visite.guidee': 'Guided Tour',
    'donnees.certifiees': 'Certified Data 2023',
    'mode.presentation': 'Presentation Mode',
    'partager': 'Share',
    'imprimer': 'Print',
    
    // Navigation & Header - EXPANDED
    'header.title': 'SAF {region}',
    'header.subtitle': 'Valorization of viticulture waste into sustainable aviation fuel',
    'nav.vue.ensemble': 'Overview',
    'nav.economie': 'Economics',
    'nav.ressources': 'Resources',
    'nav.partenaires': 'Partners',
    'nav.donnees': 'Data',
    'nav.methodologie': 'Methodology',
    'nav.contact': 'Contact',
    'nav.overview.description': 'Regional statistics and key metrics',
    'nav.resources.description': 'Analysis of available resources',
    'nav.economy.description': 'Economic tools and calculators',
    'nav.partnerships.description': 'Collaborative opportunities',
    'nav.methodology.description': 'Methodology and data sources',
    'nav.contact.description': 'Contact and next steps',
    
    // Technical Specifications
    'volume': 'Volume',
    'conversion': 'Conversion',
    'efficacite': 'Efficiency',
    'prix': 'Price',
    'tonnes.an': 'tonnes/year',
    'litres.an': 'liters/year',
    'saf.tonne': 'L SAF/tonne',
    'atj.efficiency': 'ATJ',
    'euro.per.liter': '€/L SAF',
    
    // Points Clés (Vue d'ensemble) - UPDATED TERMINOLOGY
    'points.cles': 'Key Points',
    'points.cles.subtitle': 'Essential economic and technical indicators',
    'superficie.viticole': 'Vineyard surface',
    'production.dechets.vitivinicoles': 'Annual viticulture waste production',
    'production.marc': 'Annual pomace production',
    'allocation.flux': 'Realistic Flow Allocation',
    'potentiel.saf': 'SAF Potential (70% efficiency)',
    'revenue.potential': 'Revenue Potential',
    'reduction.co2': 'CO₂ Reduction',
    'reduction.co2.potential': 'Potential CO₂ Reduction',
    'hectares': 'hectares',
    'tonnes': 'tonnes',
    'base.regionale': 'Regional base',
    'matiere.premiere.totale': 'Total raw material (all waste)',
    'matiere.premiere': 'Total raw material',
    'disponible.saf': 'available for SAF',
    'vs.fossile': 'vs fossil fuel',
    'prix.marche': 'ATJ market price',
    'revenus.annuels': 'Annual revenue',
    'emplois.crees': 'Jobs created',
    'retour.investissement': 'Return on investment',
    'ans.payback': 'Years payback',
    
    // Calculation Tooltips - NEW
    'co2.calculation.tooltip': '{liters}M liters SAF × {factor}kg CO₂/liter avoided vs fossil fuel',
    'economy.feedstock.tooltip': '{percentage}% of {total}k tonnes total biomass available for SAF',
    'infrastructure.co2.calculation.tooltip': 'Estimate: {methanization} methanization (×2.1kt) + {composting} composting (×0.8kt) + {biomass} biomass (×5kt)',
    
    // Regional Analysis
    'analyse.regionale': 'Regional Analysis',
    'analyse.regionale.subtitle': 'Territorial distribution and valorization opportunities',
    'communes.productrices': 'Top Producing Communes',
    'repartition.departementale': 'Departmental Production Distribution',
    'production.regionale': 'of regional production',
    'valorisation.methodes': 'Current Valorization Methods',
    'strategie.biomasse': 'Biomass Supply Strategy',
    'base.conservative': 'Conservative base',
    'potentiel.negociable': 'Negotiable potential',
    'total.accessible': 'Total accessible',
    'flux.elimination': 'Disposal streams',
    'surplus.excedents': 'Surplus & excess',
    'avec.partenariats': 'with partnerships',
    'disponible': 'available',
    'jusqua': 'Up to',
    'respecte.filieres': 'This approach respects established supply chains while demonstrating expansion potential to meet growing SAF demand.',
    
    // Valorization Methods - EXPANDED
    'valorization.title': 'Current Valorization Methods',
    'valorization.subtitle': 'Distribution of viticulture biomass uses',
    'valorization.distillation': 'Distillation',
    'valorization.composting': 'Composting',
    'valorization.methanization': 'Methanization', 
    'valorization.direct.spreading': 'Direct spreading',
    'valorization.percentage': 'percentage',
    'valorization.distillation.desc': 'Alcohol and spirits production',
    'valorization.composting.desc': 'Organic soil amendment',
    'valorization.methanization.desc': 'Energy biogas production',
    'valorization.spreading.desc': 'Direct vineyard application',
    'valorization.breakdown': 'Detailed Breakdown',
    'valorization.regional.context': 'Regional Context',
    'valorization.established.chains': 'Established channels',
    'valorization.mature.infrastructure': 'Mature and functional infrastructure',
    'valorization.saf.opportunity': 'SAF Opportunity',
    'valorization.new.allocation': 'new allocation available',
    'valorization.compliance': 'Regulatory compliance',
    'valorization.eu.directive': 'EU waste directive',
    'valorization.economic.impact': 'Economic impact',
    'valorization.jobs.supported': 'jobs supported',
    'valorization.methodology.note': 'Data based on IFV statistics and regional supply chain analyses',
    'tonnes.total': 'total',
    
    // Regional Context
    'contexte.regional': 'Regional Context',
    'contexte.regional.subtitle': 'National leadership and economic potential',
    'region.viticole.francaise': 'French wine region',
    'region.premium.champagne': 'Premium Champagne Region',
    'volume.production': 'By production volume',
    'marche.prestige': 'Prestige market',
    'production.nationale': 'Of national production',
    'millions.hectolitres': 'million hectoliters',
    'segment.premium': 'premium segment',
    'ca.annuel': 'Annual revenue',
    'secteur.vitivinicole': 'Regional wine industry',
    
    // Key Highlights
    'highlights.title': 'Key Highlights',
    'production.locale': 'Local production of',
    'reduction.annuelle': 'reduction of',
    'emplois.directs': 'direct and indirect jobs',
    'partenariats.communaux': 'municipal partnerships',
    
    // Business Case
    'business.case': 'Business Case',
    'mise.oeuvre': 'Implementation',
    'phase.etudes': 'Phase 1: Technical studies (6 months)',
    'phase.construction': 'Phase 2: Construction (18 months)',
    'phase.production': 'Phase 3: Production (2025)',
    'financement.total': 'Financing: €180M total',
    
    // Industry News - EXPANDED TRANSLATIONS
    'actualites.saf': 'SAF Industry News',
    'actualites.subtitle': 'Projects in development in the French supply chain',
    'investissement': 'Investment',
    'capacite': 'Capacity',
    'technologie': 'Technology',
    'partenariat': 'Partnership',
    'objectif': 'Objective',
    'budget.rd': 'R&D Budget',
    'contexte.reglementaire': 'Regulatory Context',
    'projet.inscrit': 'Our project fits into this national dynamic → See Economics tab',
    
    // Industry Players - NEW
    'industry.haffner.title': 'HAFFNER ENERGY',
    'industry.haffner.subtitle': 'Biorefinery Marolles-en-Hurepoix (Essonne)',
    'industry.lanzajet.title': 'LANZAJET',
    'industry.lanzajet.subtitle': 'Freedom Pines Fuels - Total Energies Partnership',
    'industry.lanzajet.first.commercial': 'First commercial ATJ site in Europe',
    'industry.airbus.title': 'AIRBUS',
    'industry.airbus.subtitle': 'ZEROe Programme - Green Fuels',
    'industry.airbus.hydrogen.objective': 'Hydrogen aircraft 2035',
    'industry.airbus.saf.transition': 'SAF transition',
    'industry.airbus.partnerships': 'Partnerships',
    'industry.airbus.airports': '15 French airports equipped',
    'industry.total.title': 'TOTAL ENERGIES',
    'industry.total.subtitle': 'SAF France 2030 Strategy',
    'industry.total.biorefineries': 'Biorefineries',
    'industry.total.sites.modernized': '6 modernized sites',
    'industry.total.partnerships': 'Partnerships',
    'industry.total.biomass.suppliers': '25 biomass suppliers',
    
    // Technical Terms - NEW
    'feedstock': 'Feedstock',
    'certification': 'Certification',
    'approved': 'approved',
    'capacity': 'capacity',
    'waste.agricultural.ethanol': 'Agricultural waste ethanol',
    'biomass.to.liquids': 'Biomass-to-liquids (BTL)',
    
    // Units and Common Terms
    'millions': 'million',
    'milliards': 'billion',
    'tonnes.saf.an': 'tonnes SAF/year',
    'sur.ans': 'over {years} years',
    'des.2025': 'from 2025',
    'minimum.2030': 'minimum by 2030',
    'mobilises': 'mobilized',
    'modernises': 'modernized',
    'fournisseurs.biomasse': 'biomass suppliers',
    'fonds.verts': 'green funds',
    'energies.renouvelables': 'renewable energy',
    'neutralite.carbone': 'carbon neutrality',
    'region.coming.soon': '(Coming Soon)',
    
    // Flow Allocation Terms - NEW
    'flux.proteges': 'Protected Flows',
    'flux.negociables': 'Negotiable Flows',
    'flux.disponibles': 'Available Flows',
    'non.disponible': 'Not available',
    'partenariats.requis': 'Partnerships required',
    'compost.vignobles': 'Vineyard compost',
    'biogaz.energetique': 'Energy biogas',
    'extraction.premium': 'Premium extraction',
    'surplus.saisonniers': 'Seasonal surplus',
    'excedent.compost': 'Excess compost',
    'couts.elimination': 'Current disposal costs',
    'boues.traitement': 'Treatment sludge',
    
    // Biomass Types - NEW
    'marc.raisin': 'Grape pomace',
    'sous.produits.liquides': 'Liquid byproducts',
    'bois.taille': 'Pruning wood',
    'sarments': 'Vine shoots',
    'rafles': 'Grape stems',
    'tonnage.total': 'Total tonnage',
    'types.biomasse': 'Biomass types',
    'part.total': 'Share of total',
    'communes.impliquees': 'Communes involved',
    'repartition.detaillee.biomasse': 'Detailed Biomass Breakdown',
    
    // Infrastructure - UPDATED
    'infrastructure.title': 'Processing Infrastructure',
    'infrastructure.subtitle': 'Regional transformation and valorization capacities',
    'infrastructure.distilleries': 'Distilleries',
    'infrastructure.methanization': 'Methanization units',
    'infrastructure.composting': 'Composting platforms',
    'infrastructure.biomass': 'Biomass boilers',
    'infrastructure.total.facilities': 'Total facilities',
    'infrastructure.existing.capacity': 'Existing capacity',
    'infrastructure.disclaimer': 'Estimates based on existing infrastructure and average capacities per facility type',
    'co2.evite.annuel': 'Annual CO₂ avoided',
    
    // Seasonal Terms - NEW
    'disponibilite.saisonniere': 'Seasonal Resource Availability',
    'vue.lineaire': 'Linear View',
    'vue.circulaire': 'Circular View',
    'maintenance': 'Maintenance',
    'planning': 'Planning',
    'lies': 'Lees',
    'formation': 'Training',
    'preparation': 'Preparation',
    'contrats': 'Contracts',
    'veille': 'Monitoring',
    'optimisation': 'Optimization',
    'tests': 'Testing',
    'mobilisation': 'Mobilization',
    'coordination': 'Coordination',
    'stockage': 'Storage',
    'bilan': 'Assessment',
    'planification': 'Planning',
    'legende.intensite': 'Intensity Legend:',
    'peak': 'Peak (80-100%)',
    'eleve': 'High (60-80%)',
    'moyen': 'Medium (40-60%)',
    'faible': 'Low (0-40%)',
    
    // Economy Tab - NEW SECTION
    'economy.title': 'Economic Analysis - {region}',
    'economy.subtitle': 'Financial modeling and profitability analysis by region',
    'economy.regional.context': 'Regional Economic Context',
    'economy.investment.opportunity': 'Investment opportunity based on local resources',
    'economy.available.feedstock': 'Available feedstock',
    'economy.biomass.secured': 'Secured biomass',
    'economy.saf.production': 'SAF Production',
    'economy.annual.revenue': 'Annual revenue',
    'economy.market.price': 'ATJ market price',
    'economy.jobs.created': 'Jobs created',
    'economy.direct.employment': 'Direct employment',
    'economy.analysis.modules': 'Economic Analysis Modules',
    'economy.financial.modeling': 'Financial modeling tools and profitability assessment',
    'economy.roi.calculator': 'ROI Calculator',
    'economy.cost.benefit': 'Cost-Benefit',
    'economy.projections': 'Projections',
    'economy.roi.title': 'ROI Calculator',
    'economy.roi.description': 'Return on investment based on {tonnage}kt available',
    'economy.cost.benefit.title': 'Cost-Benefit Analysis',
    'economy.cost.benefit.description': 'Detailed investment and return assessment',
    'economy.projections.title': 'Economic Projections',
    'economy.projections.description': '5-year financial forecasts',
    'economy.financing.overview': 'Financing - Overview',
    'economy.equity.funding': 'Equity funding',
    'economy.equity.percentage': '30-40% total',
    'economy.bank.debt': 'Bank debt',
    'economy.interest.rate': 'Rate 4-6%',
    'economy.subsidies': 'Subsidies',
    'economy.eu.france.funding': 'EU + France 2030',
    'economy.total.investment': 'Total investment',
    'economy.capacity.description': 'Capacity {capacity}kt SAF/year',
    'economy.scaling.note': 'Investment scaled to {region} regional capacity ({capacity}kt available biomass)',
    'economy.market.advantage': 'Competitive Advantages',
    'economy.competitive.positioning': 'Strategic positioning in SAF market',
    'economy.feedstock.security': 'Feedstock Security',
    'economy.local.supply.chain': 'Local supply chain',
    'economy.waste.stream.cost': 'Negative feedstock cost',
    'economy.year.round.availability': 'Year-round availability',
    'economy.established.logistics': 'Established logistics',
    'economy.regulatory.advantage': 'Regulatory Advantages',
    'economy.eu.saf.mandates': 'EU SAF mandates',
    'economy.carbon.credit.revenue': 'Carbon credit revenue',
    'economy.france.2030.support': 'France 2030 support',
    'economy.waste.directive.compliance': 'Waste directive compliance',
    'economy.geographic.benefits': 'Geographic Benefits',
    'economy.proximity.airports': 'Airport proximity',
    'economy.distribution.network': 'Distribution network',
    'economy.skilled.workforce': 'Skilled workforce',
    'economy.industrial.infrastructure': 'Industrial infrastructure',
    
    // ROI Calculator Translation Keys - NEW
    'roi.calculator.title': 'Advanced ROI Calculator',
    'roi.real.data': 'Real Data',
    'roi.export': 'Export',
    'roi.conservative': 'Conservative',
    'roi.realistic': 'Realistic',
    'roi.optimistic': 'Optimistic',
    'roi.scenario.parameters': 'Scenario Parameters',
    'roi.parameters.sources': 'Parameter Sources (Research-Based):',
    'roi.biomass.range': '40-120k tonnes',
    'roi.biomass.explanation': 'Realistic allocation of available viticulture waste for SAF (ATJ Technology Assessment, IEA Bioenergy 2021)',
    'roi.efficiency.range': '65-75%',
    'roi.efficiency.explanation': 'Validated ATJ technology efficiency (Honeywell UOP, BP, Total Energies industry benchmarks)',
    'roi.price.range': '€1.10-1.35/L',
    'roi.price.explanation': 'IATA SAF projections 2025-2027 + CORSIA premiums for certified sustainable fuels',
    'roi.costs.range': '€0.75-0.95/L',
    'roi.costs.explanation': 'Operating costs including biomass processing and scale economies (IRENA Renewable Energy 2021)',
    'roi.investment.range': '€1.4-1.5M/kt',
    'roi.investment.explanation': 'SAF industry CAPEX based on Neste, Shell, TotalEnergies projects (€85-150M for 60-100kt capacity)',
    'roi.biomass.input': 'Biomass input (tonnes/year)',
    'roi.process.efficiency': 'Process efficiency (%)',
    'roi.saf.price': 'SAF price',
    'roi.operating.costs': 'Operating costs',
    'roi.capital.investment': 'Capital investment (M€)',
    'roi.saf.production.annual': 'Liters SAF/year',
    'roi.five.year': 'ROI (5 years)',
    'roi.payback.years': 'Payback years',
    'roi.irr': 'IRR',
    'roi.revenue.costs.annual': 'Annual Revenue & Costs',
    'roi.gross.revenue': 'Gross revenue',
    'roi.operating.costs': 'Operating costs',
    'roi.gross.profit': 'Gross profit',
    'roi.financial.indicators': 'Financial Indicators',
    'roi.npv.ten.years': 'NPV (10 years, 8%)',
    'roi.gross.margin': 'Gross margin',
    'roi.capital.required': 'Capital required',
    
    // Cost-Benefit Analysis Translation Keys - NEW
    'cost.benefit.title': 'Cost-Benefit Analysis',
    'cost.benefit.comparison': 'Comparison',
    'cost.benefit.timeline': 'Timeline',
    'cost.benefit.breakdown': 'Breakdown',
    'cost.benefit.revenue': 'Revenue',
    'cost.benefit.operating.costs': 'Operating costs',
    'cost.benefit.net.profit': 'Net profit',
    'cost.benefit.jobs.created': 'Jobs created',
    'cost.benefit.co2.avoided': 'CO₂ avoided (kt)',
    'cost.benefit.profit.improvement': 'Profit improvement',
    'cost.benefit.additional.benefit': 'Additional benefit',
    'cost.benefit.co2.avoided.annual': 'CO₂ avoided/year',
    'cost.benefit.real.data': 'Real data',
    'cost.benefit.traditional.valorization': 'Traditional valorization (M€)',
    'cost.benefit.saf.valorization': 'SAF valorization (M€)',
    'cost.benefit.detailed.comparison': 'Detailed Comparison',
    'cost.benefit.category': 'Category',
    'cost.benefit.traditional': 'Traditional',
    'cost.benefit.saf': 'SAF',
    'cost.benefit.difference': 'Difference',
    'cost.benefit.improvement': 'Improvement',
    'cost.benefit.traditional.annual': 'Traditional (M€/year)',
    'cost.benefit.saf.annual': 'SAF (M€/year)',
    'cost.benefit.saf.cumulative': 'SAF Cumulative (M€)',
    'cost.benefit.breakeven.point': 'Breakeven point',
    'cost.benefit.investment.return': 'Return on investment',
    'cost.benefit.cumulative.profit': 'Cumulative profit',
    'cost.benefit.over.six.years': 'Over 6 years',
    'cost.benefit.annual.growth': 'Annual growth',
    'cost.benefit.average.2025.2029': 'Average 2025-2029',
    'cost.benefit.saf.cost.breakdown': 'SAF Cost Breakdown',
    'cost.benefit.biomass.collection': 'Biomass collection',
    'cost.benefit.pretreatment': 'Pretreatment',
    'cost.benefit.atj.conversion': 'ATJ conversion',
    'cost.benefit.refining': 'Refining',
    'cost.benefit.distribution': 'Distribution',
    'cost.benefit.regional.economic.impact': 'Regional Economic Impact',
    'cost.benefit.direct.jobs': 'Direct jobs',
    'cost.benefit.positions': 'positions',
    'cost.benefit.production.maintenance': 'Production and maintenance',
    'cost.benefit.indirect.jobs': 'Indirect jobs',
    'cost.benefit.services.suppliers': 'Services and suppliers',
    'cost.benefit.local.taxes': 'Local taxes',
    'cost.benefit.municipal.revenue': 'Municipal revenue',
    'cost.benefit.local.purchases': 'Local purchases',
    'cost.benefit.circular.economy': 'Circular economy',
    'cost.benefit.context': 'Context',
    'cost.benefit.champagne.context': 'Analysis adapted to premium scale with lower volumes but higher margins.',
    'cost.benefit.languedoc.context': 'Modeling based on large volumes and established regional infrastructure.',
    
    // Commune Production - NEW
    'repartition.production.commune': 'Production Distribution by Commune',
    'communes.principales': 'Top Producing Communes',
    'production.regionale.percent': 'of regional production',
    
    // Resources Tab - EXTENDED
    'resources.title': 'Biomass Resources',
    'resources.subtitle': 'Mapping and analysis of available regional resources',
    'resources.biomassTotal': 'Total Biomass',
    'resources.availableForSAF': 'Available for SAF',
    'resources.safProduction': 'SAF Production',
    'resources.revenuesPotential': 'Revenue Potential',
    'resources.allocationTitle': 'Realistic Flow Allocation',
    'resources.allocationSubtitle': 'Effective availability for SAF production',
    'resources.total.biomass.regional': 'Total Regional Viticulture Biomass',
    'resources.totalProduction': 'Total theoretical production',
    'resources.totalPercentage': '100% of biomass resources',
    'resources.realisticAllocation': 'realistic allocation',
    'resources.otherValorisations': 'Other valorizations',
    'resources.otherValorisationsDesc': 'Distillation, composting, methanization',
    'resources.whyThirtyPercent.title': 'Why only 30%?',
    'resources.whyThirtyPercent.description': 'Existing distilleries, logistical constraints, seasonality and local needs limit real availability for new SAF projects.',
    'resources.analysisTitle': 'Resource Analysis',
    'resources.analysisSubtitle': 'Distribution and seasonality of available biomass',
    'resources.infrastructureTitle': 'Existing Infrastructure',
    'resources.infrastructureSubtitle': 'Processing and valorization capacities',
    'resources.safPotentialTitle': 'SAF Production Potential',
    'resources.safPotentialSubtitle': 'Realistic capacity based on {tonnage} available tonnes',
    'resources.annualSafProduction': 'Annual SAF production',
    'resources.yieldRate': 'At 280L/tonne yield rate',
    'resources.potentialRevenue': 'Potential revenue',
    'resources.pricePerLiter': 'At €1.22/L selling price',
    'resources.annualCo2Avoided': 'Annual CO₂ avoided',
    'resources.vsFossilFuel': 'vs fossil fuel',
    'resources.disclaimer': '* Estimates based on ATJ (Alcohol-to-Jet) technologies and current market conditions',
    
    // Contact Tab - NEW ADDITIONS
    'contact.title': 'Contact & Next Steps',
    'contact.subtitle': 'Transform vineyard waste into future opportunities together',
    'contact.businessOpportunities': 'Collaboration Opportunities',
    'contact.strategicPartnership': 'Strategic Partnership',
    'contact.strategicDesc': 'Collaboration and commercial agreements',
    'contact.investmentOpportunity': 'Investment Opportunity',
    'contact.investmentDesc': 'Financial participation in the project',
    'contact.technicalSupport': 'Technical Support',
    'contact.technicalDesc': 'Technical questions and feasibility',
    'contact.generalInfo': 'General Information',
    'contact.generalDesc': 'Project information requests',
    'contact.regionalPotential': 'Regional Potential',
    'contact.directContact': 'Direct Contact',
    'contact.directLine': 'Direct line',
    'contact.generalEmail': 'General email',
    'contact.scheduleMeeting': 'Schedule Meeting',
    'contact.contactForm': 'Contact Form',
    'contact.fullName': 'Full name',
    'contact.yourName': 'Your name',
    'contact.phone': 'Phone',
    'contact.company': 'Company/Organization',
    'contact.companyPlaceholder': 'Your company name',
    'contact.role': 'Role/Position',
    'contact.yourPosition': 'Your position',
    'contact.preferredContact': 'Preferred contact method',
    'contact.telephone': 'Telephone',
    'contact.meeting': 'Meeting',
    'contact.interests': 'Areas of interest (select all that apply)',
    'contact.feasibilityStudy': 'Feasibility study',
    'contact.projectTimeline': 'Project timeline',
    'contact.environmentalImpact': 'Environmental impact',
    'contact.economicBenefits': 'Economic benefits',
    'contact.detailedMessage': 'Detailed message',
    'contact.messagePlaceholder': 'Describe your needs, questions or proposals...',
    'contact.sendInquiry': 'Send Inquiry',
    'contact.afterInquiry': 'After your inquiry',
    'contact.guaranteedResponse': 'Guaranteed response',
    'contact.firstMeeting': 'First meeting',
    'contact.detailedProposal': 'Detailed proposal',
    'contact.thankYou': 'Thank you for your inquiry!',
    'contact.thankYouMessage': 'We will contact you within 48 hours to discuss collaboration opportunities.',
    'contact.newInquiry': 'New inquiry',
    'contact.otherContactMethods': 'Other ways to contact us',
    'contact.projectInfoRequest': 'Project information requests',
    
    // Time and Units - EXTENDED
    'time.week': 'week',
    'time.month': 'month',
    'time.hours48': '48h',
    'units.tonesYear': 'tonnes/year',
    'units.litersYear': 'liters/year',
    'units.hectares': 'hectares',
    'units.ofTotal': 'of total',
    'units.potential': 'potential',
    'units.estimated': 'estimated',
    
    // Footer translations
    'footer.project.description': 'Valorization of grape pomace into sustainable aviation fuel. Pioneer project for transforming viticultural waste into certified SAF.',
    'footer.revenues': 'revenues',
    'footer.co2.avoided': 'CO₂ avoided',
    'footer.methodology.standards': 'Methodology & Standards',
    'footer.certifications.audits': 'Certifications & Audits',
    'footer.institutional.partners': 'Institutional Partners',
    'footer.primary.data.sources': 'Primary Data Sources',
    'footer.scientific.validation': 'Scientific Validation',
    'footer.international.standards': 'International Standards',
    'footer.copyright': 'SAF {region} Project. All rights reserved.',
    'footer.data.updated': 'Data updated: December 2023',
    'footer.next.revision': 'Next revision: March 2024',
    'footer.legal.notices': 'Legal notices',
    'footer.data.protection': 'Data protection',
    'footer.terms.of.use': 'Terms of use',
    'footer.disclaimer.title': 'Disclaimer:',
    'footer.disclaimer.text': 'Financial and technical projections are based on real 2023 data and assumptions validated by independent experts. Future results may vary according to market conditions. This document does not constitute investment advice.',
    
    // Methodology
    'methodology.atj.title': 'ATJ Methodology',
    'methodology.atj.description': 'ASTM D7566 certified Alcohol-to-Jet process',
    'methodology.agreste.title': 'Agreste Data',
    'methodology.agreste.description': 'Official French agricultural statistics',
    'methodology.ifv.title': 'IFV Institute',
    'methodology.ifv.description': 'French Institute of Vine and Wine',
    'methodology.corsia.title': 'CORSIA Standards',
    'methodology.corsia.description': 'ICAO Carbon Offsetting Scheme',
    
    // Credentials
    'credentials.bureau.veritas': 'Data certified by Bureau Veritas',
    'credentials.astm.compliance': 'ASTM D7566 & EN 15940 compliance',
    'credentials.corsia.validation': 'CORSIA validation for carbon credits',
    'credentials.quarterly.audit': 'Independent quarterly audit',
    'credentials.peer.reviewed': 'Peer-reviewed methodology',
    
    // Partners - Languedoc
    'partners.region.occitanie': 'Occitanie Region',
    'partners.ifv': 'French Institute of Vine (IFV)',
    'partners.safer.languedoc': 'SAFER Languedoc',
    'partners.chamber.herault': 'Hérault Chamber of Agriculture',
    'partners.vignerons.union': 'Winegrowers Union',
    
    // Partners - Champagne
    'partners.region.grand.est': 'Grand Est Region',
    'partners.safer.champagne': 'SAFER Champagne',
    'partners.chamber.champagne': 'Champagne Chamber of Agriculture',
    'partners.champagne.union': 'General Union of Champagne Winegrowers',
    
    // Data Sources
    'data.sources.agreste': 'Agreste - National agricultural statistics',
    'data.sources.ifv': 'IFV - Wine production and yields',
    'data.sources.oiv': 'OIV - International standards',
    'data.sources.aviation.fuel': 'Aviation Fuel Analytics - SAF pricing',
    
    // Validation
    'validation.peer.review': 'Peer-review by scientific committee',
    'validation.bureau.veritas': 'Bureau Veritas validation',
    'validation.iso.compliance': 'ISO 14064 & 14067 compliance',
    'validation.carbon.audit': 'Third-party independent carbon audit',
    
    // Standards
    'standards.astm.d7566': 'ASTM D7566 - Jet fuel specifications',
    'standards.corsia.icao': 'CORSIA - ICAO carbon offsetting',
    'standards.red.ii': 'RED II - Renewable Energy Directive',
    'standards.iscc.eu': 'ISCC EU - Sustainability certification',
    
    // Tooltip
    'tooltip.source': 'Source: Agreste 2023, OIV data'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');
  const [debugMode, setDebugMode] = useState<boolean>(false);
  const [missingTranslations, setMissingTranslations] = useState<string[]>([]);

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key];
    
    // Track missing translations in debug mode
    if (!translation && debugMode) {
      if (!missingTranslations.includes(key)) {
        setMissingTranslations(prev => [...prev, key]);
        console.warn(`Missing translation: ${key}`);
      }
      return `[MISSING: ${key}]`;
    }
    
    // Fallback to key if translation not found
    if (!translation) {
      translation = key;
    }
    
    // Handle parameter replacement like {region}, {years}, {tonnage}, etc.
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param]);
      });
    }
    
    return translation;
  };

  const getMissingTranslations = (): string[] => {
    return [...missingTranslations];
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t, 
      debugMode, 
      setDebugMode,
      getMissingTranslations 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
