import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
  // Debug helpers
  debugMode: boolean;
  setDebugMode: (enabled: boolean) => void;
  getMissingTranslations: () => string[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Main Atlas Headers
    'atlas.title': 'Atlas Biomasse Vitivinicole',
    'region.subtitle': 'Potentiel de valorisation en carburant aviation durable',
    
    // Navigation & Interface
    'visite.guidee': 'Visite Guidée',
    'donnees.certifiees': 'Données Certifiées 2023',
    'mode.presentation': 'Mode Présentation',
    'partager': 'Partager',
    'imprimer': 'Imprimer',
    
    // Navigation & Header - EXPANDED
    'header.title': 'SAF {region}',
    'header.subtitle': 'Valorisation des déchets vitivinicoles en carburant aviation durable',
    'nav.vue.ensemble': 'Vue d\'ensemble',
    'nav.economie': 'Économie',
    'nav.ressources': 'Ressources',
    'nav.partenaires': 'Partenaires',
    'nav.donnees': 'Données',
    'nav.methodologie': 'Méthodologie',
    'nav.contact': 'Contact',
    'nav.overview.description': 'Statistiques régionales et métriques clés',
    'nav.resources.description': 'Analyse des ressources disponibles',
    'nav.economy.description': 'Outils économiques et calculateurs',
    'nav.partnerships.description': 'Opportunités collaboratives',
    'nav.methodology.description': 'Méthodologie et sources de données',
    'nav.contact.description': 'Informations de contact et support',
    
    // Regional Data & Statistics
    'region.current': 'Région actuelle',
    'donnees.regionales': 'Données Régionales',
    'surface.viticole': 'Surface Viticole',
    'production.annuelle': 'Production Annuelle',
    'production.waste': 'Production annuelle de déchets vitivinicoles',
    'production.total.biomass': 'Production totale de biomasse',
    'production.marc': 'Production annuelle de marc',
    'production.regionale': 'Production Régionale',
    'repartition.departementale': 'Répartition Départementale',
    'repartition.production.commune': 'Répartition de la Production par Commune',
    'communes.principales': 'Principales Communes Productrices',
    'disponible': 'Disponible',
    'jusqua': 'Jusqu\'à',
    
    // Overview Tab - COMPLETE WITH NEW BANNER & MARKET VALIDATION
    'points.cles': 'Points Clés',
    'points.cles.subtitle': 'Indicateurs régionaux de performance',
    'superficie.viticole': 'Surface Viticole',
    'base.regionale': 'Base Régionale',
    'production.dechets.vitivinicoles': 'Production déchets vitivinicoles',
    'matiere.premiere.totale': 'Matière première totale',
    'allocation.flux': 'Allocation flux',
    'disponible.saf': 'Disponible SAF',
    'potentiel.saf': 'Potentiel SAF',
    'revenue.potential': 'Potentiel revenus',
    'reduction.co2.potential': 'Potentiel réduction CO₂',
    'vs.fossile': 'vs fossile',
    'co2.calculation.tooltip': '15.7M litres SAF × 2.5kg CO₂/litre évité vs carburant fossile',
    'analyse.regionale': 'Analyse Régionale',
    'analyse.regionale.subtitle': 'Répartition et potentiel par zone géographique',
    'production.regionale.percent': 'Production Régionale',
    'saf.potential': 'Potentiel SAF',
    'base.sur.disponibles': 'Basé sur 80k tonnes disponibles',
    
    // Banner & Transformation Section
    'banner.transform.title': 'Transformer les Déchets Viticoles en SAF',
    'banner.waste.regional': 'déchets régionaux',
    'banner.valorizable': 'valorisables',
    'banner.respects.existing': 'Respecte les filières existantes',
    
    // Market Validation - IATA Section  
    'market.validation.title': 'Validation du Marché International',
    'market.validation.subtitle': 'Les dernières données IATA confirment l\'opportunité stratégique',
    'iata.report.title': 'IATA Global Feedstock Assessment 2025',
    'iata.report.subtitle': 'Validation de la Stratégie des Résidus Agricoles',
    'iata.deficit.saf': 'Déficit SAF',
    'iata.deficit.desc': '100 Mt manquantes d\'ici 2050',
    'iata.agricultural.residues': 'Résidus Agricoles',
    'iata.agricultural.desc': '58% des matières premières prioritaires',
    'iata.europe': 'Europe',
    'iata.europe.desc': 'Top 4 mondial pour développement',
    'iata.etj.technology': 'Technologie EtJ',
    'iata.etj.desc': 'Voie validée pour matières agricoles',
    'iata.source': 'Source: IATA Global Feedstock Assessment for SAF Production Outlook to 2050 - Janvier 2025',
    
    // Market Opportunity
    'market.opportunity.title': 'Opportunité de Marché',
    'market.demand.2050': 'Demande SAF 2050',
    'market.production.forecast': 'Production prévue',
    'market.deficit.gap': 'DÉFICIT À COMBLER',
    
    // Regional Implementation
    'regional.implementation.title': 'Mise en Œuvre Régionale',
    'regional.implementation.subtitle': 'Infrastructure existante et stratégie biomasse respectueuse',
    'regional.advantages.title': 'Avantages Compétitifs Régionaux',
    'regional.advantages.subtitle': 'Infrastructure mature et leadership viticole français',
    
    // Industry Momentum
    'industry.momentum.title': 'Dynamique Industrielle',
    'industry.momentum.subtitle': 'Projets de référence et soutien réglementaire',
    'industry.reference.projects': 'Projets de Référence',
    'industry.major.industrials': 'Majors Industriels',
    'industry.airbus.program.desc': 'Avion hydrogène 2035 • 10% SAF minimum 2030 • €15B R&D',
    'industry.total.strategy.desc': '€500M sur 5 ans • 1.5M t SAF/an • 6 bioraffineries modernisées',
    'industry.regulatory.support': 'Soutien Réglementaire',
    'regulatory.saf.minimum': 'SAF minimum 2025 (EU)',
    'regulatory.france.2030': 'France 2030',
    'regulatory.eu.repower': 'EU REPowerEU',
    'regulatory.carbon.neutral': 'Neutralité carbone',
    
    // Call-to-Action Section
    'cta.strategic.opportunity': 'Une Opportunité Stratégique à Saisir',
    'cta.transform.challenge': 'Transformer le défi des déchets viticoles en avantage concurrentiel SAF',
    'cta.timing.optimal': 'Timing Optimal',
    'cta.timing.desc': 'Réglementation favorable + demande croissante',
    'cta.first.mover': 'First-Mover',
    'cta.first.mover.desc': 'Contrainte = déploiement, pas ressources',
    'cta.win.win': 'Gagnant-Gagnant',
    'cta.win.win.desc': 'Respecte filières + crée valeur',
    
    // Overview Tab Metrics - RESTORED
    'metriques.cles': 'Métriques Clés',
    'hectares': 'hectares',
    'tonnes.annee': 'tonnes/an',
    'producteurs': 'producteurs',
    'communes': 'communes',
    'communes.tracked': 'Communes suivies',
    'communes.total.production': 'Production totale communes',
    'communes.coverage': 'Couverture communes',
    'communes.methodology.note': 'Méthodologie basée sur les données départementales 2023',
    'industries.cles': 'Industries Clés',
    'cooperatives': 'Coopératives',
    'distilleries': 'Distilleries',
    'sites.methanisation': 'Sites de Méthanisation',
    'installations.compostage': 'Installations de Compostage',
    
    // Resources Tab - RESTORED ALL MISSING KEYS
    'resources.title': 'Ressources Disponibles',
    'resources.subtitle': 'Analyse détaillée des flux de biomasse et infrastructure',
    'resources.allocationTitle': 'Stratégie d\'Allocation des Flux',
    'resources.allocationSubtitle': 'Répartition des 266,000 tonnes de biomasse par destination',
    'resources.total.biomass.regional': 'Biomasse totale régionale',
    'non.disponible': 'Non disponible',
    'compost.vignobles': 'Compost vignobles',
    'biogaz.energetique': 'Biogaz énergétique',
    'extraction.premium': 'Extraction premium',
    'surplus.excedents': 'Surplus excédents',
    'excedent.compost': 'Excédent compost',
    'couts.elimination': 'Coûts élimination',
    'boues.traitement': 'Boues traitement',
    'repartition.detaillee.biomasse': 'Répartition Détaillée de la Biomasse',
    'tonnage.total': 'Tonnage total',
    'part.total': 'Part totale',
    'communes.impliquees': 'Communes impliquées',
    
    // Infrastructure - RESTORED MISSING KEYS
    'infrastructure.methanization': 'Méthanisation',
    'infrastructure.composting': 'Compostage',
    'infrastructure.biomass': 'Biomasse',
    'co2.evite.annuel': 'CO₂ évité annuel',
    'infrastructure.co2.calculation.tooltip': 'Estimation: 27 méthanisation (×2.1kt) + 26 compostage (×0.8kt) + 4 biomasse (×5kt)',
    'infrastructure.total.facilities': 'Installations totales',
    'infrastructure.existing.capacity': 'Capacité existante',
    'infrastructure.disclaimer': 'Méthodologie basée sur les données sectorielles 2023',
    
    // Seasonal Timeline - RESTORED INTENSITY LEVELS
    'peak': 'Peak',
    'eleve': 'Élevé',
    'moyen': 'Moyen',
    'faible': 'Faible',
    'preparation': 'Préparation',
    'contrats': 'Contrats',
    'veille': 'Veille',
    'optimisation': 'Optimisation',
    'tests': 'Tests',
    'mobilisation': 'Mobilisation',
    'coordination': 'Coordination',
    'stockage': 'Stockage',
    'bilan': 'Bilan',
    'planification': 'Planification',
    
    // Valorization - RESTORED MISSING KEYS
    'valorization.title': 'Méthodes de Valorisation Actuelles',
    'valorization.subtitle': 'Répartition des flux de biomasse par filière',
    'valorization.breakdown': 'Répartition valorisation',
    'valorization.distillation': 'Distillation',
    'valorization.distillation.desc': 'Production d\'alcool et spiritueux',
    'valorization.composting': 'Compostage',
    'valorization.composting.desc': 'Amendements organiques',
    'valorization.methanization': 'Méthanisation',
    'valorization.methanization.desc': 'Production biogaz et digestat',
    'valorization.direct.spreading': 'Épandage direct',
    'valorization.spreading.desc': 'Amendement direct des sols',
    'valorization.regional.context': 'Contexte Régional',
    'valorization.established.chains': 'Chaînes établies',
    'valorization.mature.infrastructure': 'Infrastructure mature',
    'valorization.saf.opportunity': 'Opportunité SAF',
    'valorization.new.allocation': 'Nouvelle allocation',
    'valorization.compliance': 'Conformité',
    'valorization.eu.directive': 'Directive UE déchets',
    'valorization.economic.impact': 'Impact économique',
    'valorization.jobs.supported': 'emplois soutenus',
    'valorization.methodology.note': 'Méthodologie basée sur les données sectorielles 2023',
    
    // Strategy & Context - RESTORED
    'strategie.biomasse': 'Stratégie Biomasse',
    'base.conservative': 'Base conservative',
    'flux.elimination': 'Flux élimination',
    'surplus.excedents': 'Surplus excédents',
    'total.accessible': 'Total accessible',
    'avec.partenariats': 'Avec partenariats',
    'respecte.filieres': 'Respecte filières existantes',
    'contexte.regional': 'Contexte Régional',
    'contexte.regional.subtitle': 'Position stratégique dans l\'écosystème vitivinicole français',
    'region.viticole.francaise': 'région viticole française',
    'volume.production': 'Volume production',
    'production.nationale': 'Production nationale',
    'millions': 'millions',
    'ca.annuel': 'CA annuel',
    'secteur.vitivinicole': 'Secteur vitivinicole',
    
    // Industry News - RESTORED ALL KEYS  
    'actualites.saf': 'Actualités SAF',
    'actualites.subtitle': 'Développements récents dans l\'industrie',
    'industry.haffner.title': 'Haffner Energy',
    'industry.haffner.subtitle': 'Premier projet SAF à grande échelle en France',
    'investissement': 'Investissement',
    'capacite': 'Capacité',
    'tonnes.saf.an': 'tonnes SAF/an',
    'des.2025': 'dès 2025',
    'technologie': 'Technologie',
    'partenariat': 'Partenariat',
    'industry.lanzajet.title': 'LanzaJet',
    'industry.lanzajet.subtitle': 'Première raffinerie commerciale SAF aux États-Unis',
    'industry.lanzajet.first.commercial': 'Première raffinerie commerciale',
    'waste.agricultural.ethanol': 'Éthanol agricole et déchets',
    'industry.airbus.title': 'Airbus',
    'industry.airbus.subtitle': 'Objectifs ambitieux pour l\'aviation verte',
    'industry.airbus.hydrogen.objective': '100% hydrogène 2035',
    'industry.airbus.saf.transition': 'Transition SAF',
    'minimum.2030': 'Minimum 2030',
    'industry.airbus.partnerships': 'Partenariats aéroportuaires',
    'industry.airbus.airports': 'Aéroports européens',
    'budget.rd': 'Budget R&D',
    'milliards': 'milliards',
    'mobilises': 'mobilisés',
    'industry.total.title': 'Total Energies',
    'industry.total.subtitle': 'Stratégie intégrée biocarburants',
    'sur.ans': 'Sur 5 ans',
    'objectif': 'Objectif',
    'industry.total.biorefineries': 'Bioraffineries',
    'industry.total.sites.modernized': '6 sites modernisés',
    'industry.total.partnerships': 'Partenariats',
    'industry.total.biomass.suppliers': 'Fournisseurs biomasse',
    
    // Regulatory Context - RESTORED
    'contexte.reglementaire': 'Contexte Réglementaire',
    'fonds.verts': 'Fonds verts',
    'energies.renouvelables': 'Énergies renouvelables',
    'neutralite.carbone': 'Neutralité carbone 2050',
    'projet.inscrit': 'Projet inscrit dans la stratégie nationale',
    
    // Footer & Methodology - RESTORED ALL KEYS
    'footer.project.description': 'Valorisation des déchets vitivinicoles en carburant aviation durable',
    'footer.revenues': 'Revenus potentiels',
    'footer.co2.avoided': 'CO₂ évité',
    'footer.methodology.standards': 'Standards Méthodologiques',
    'methodology.atj.title': 'Technologie ATJ',
    'methodology.atj.description': 'Alcohol-to-Jet certifiée ASTM D7566',
    'methodology.agreste.title': 'Données Agreste',
    'methodology.agreste.description': 'Statistiques agricoles officielles',
    'methodology.ifv.title': 'Institut IFV',
    'methodology.ifv.description': 'Recherche vitivinicole française',
    'methodology.corsia.title': 'Standards CORSIA',
    'methodology.corsia.description': 'Validation OACI internationale',
    'footer.certifications.audits': 'Certifications et Audits',
    'credentials.bureau.veritas': 'Vérification Bureau Veritas',
    'credentials.astm.compliance': 'Conformité ASTM D7566',
    'credentials.corsia.validation': 'Validation CORSIA',
    'credentials.quarterly.audit': 'Audit trimestriel',
    'credentials.peer.reviewed': 'Revue par les pairs',
    'footer.institutional.partners': 'Partenaires Institutionnels',
    'partners.region.occitanie': 'Région Occitanie',
    'partners.ifv': 'Institut Français de la Vigne',
    'partners.safer.languedoc': 'SAFER Languedoc',
    'partners.chamber.herault': 'Chambre Agriculture Hérault',
    'partners.vignerons.union': 'Union des Vignerons',
    'footer.primary.data.sources': 'Sources de Données Primaires',
    'data.sources.agreste': 'Statistiques Agreste',
    'data.sources.ifv': 'Recherche IFV',
    'data.sources.oiv': 'Organisation Internationale Vigne',
    'data.sources.aviation.fuel': 'Aviation Fuel Analytics',
    'footer.scientific.validation': 'Validation Scientifique',
    'validation.peer.review': 'Revue par les pairs',
    'validation.bureau.veritas': 'Audit Bureau Veritas',
    'validation.iso.compliance': 'Conformité ISO',
    'validation.carbon.audit': 'Audit carbone',
    'footer.international.standards': 'Standards Internationaux',
    'standards.astm.d7566': 'ASTM D7566',
    'standards.corsia.icao': 'CORSIA OACI',
    'standards.red.ii': 'RED II',
    'standards.iscc.eu': 'ISCC EU',
    
    // Economy Tab - COMPLETE WITH ALL SECTIONS
    'economy.title': 'Analyse Économique',
    'economy.subtitle': 'Modélisation financière et opportunités d\'investissement',
    'economy.cost.benefit.title': 'Analyse Coût-Bénéfice',
    'economy.cost.benefit.description': 'Comparaison économique entre valorisation traditionnelle et production SAF',
    'economy.projections.title': 'Projections Économiques',
    'economy.projections.description': 'Évolution financière et impact régional sur 5-10 ans',
    'economy.regional.context': 'Contexte économique régional',
    'economy.investment.opportunity': 'Opportunité d\'investissement',
    'economy.available.feedstock': 'Matière première disponible',
    'economy.biomass.secured': 'Biomasse sécurisée',
    'economy.feedstock.tooltip': '30% de 266k tonnes biomasse totale disponible pour SAF',
    'economy.saf.production': 'Production SAF',
    'economy.annual.revenue': 'Revenus annuels',
    'economy.market.price': 'Prix du marché',
    'economy.jobs.created': 'Emplois créés',
    'economy.direct.employment': 'Emploi direct',
    'economy.analysis.modules': 'Modules d\'Analyse',
    'economy.financial.modeling': 'Modélisation Financière',
    'economy.roi.calculator': 'Calculateur ROI',
    'economy.cost.benefit': 'Coût-Bénéfice',
    'economy.projections': 'Projections',
    'economy.roi.title': 'Calculateur ROI Avancé',
    'economy.roi.description': 'Analyse de rentabilité avec données régionales certifiées',
    'roi.calculator.title': 'Calculateur ROI',
    'roi.real.data': 'Données Réelles',
    'roi.export': 'Exporter',
    'roi.conservative': 'Conservateur',
    'roi.realistic': 'Réaliste',
    'roi.optimistic': 'Optimiste',
    'roi.scenario.parameters': 'Paramètres du Scénario',
    'roi.biomass.input': 'Intrant biomasse',
    'roi.process.efficiency': 'Efficacité procédé',
    'roi.saf.price': 'Prix SAF',
    'roi.operating.costs': 'Coûts opérationnels',
    'roi.capital.investment': 'Investissement capital',
    'roi.saf.production.annual': 'Production SAF annuelle',
    'roi.five.year': 'ROI 5 ans',
    'roi.payback.years': 'Retour sur investissement',
    'roi.irr': 'TRI',
    'roi.revenue.costs.annual': 'Revenus et Coûts Annuels',
    'roi.gross.revenue': 'Revenus bruts',
    'roi.operating.costs': 'Coûts opérationnels',
    'roi.gross.profit': 'Profit brut',
    'roi.financial.indicators': 'Indicateurs Financiers',
    'roi.npv.ten.years': 'VAN 10 ans',
    'roi.gross.margin': 'Marge brute',
    'roi.capital.required': 'Capital requis',
    'economy.market.advantage': 'Avantage Marché',
    'economy.competitive.positioning': 'Positionnement Concurrentiel',
    'economy.feedstock.security': 'Sécurité Approvisionnement',
    'economy.local.supply.chain': 'Chaîne locale',
    'economy.waste.stream.cost': 'Coût flux déchets',
    'economy.year.round.availability': 'Disponibilité annuelle',
    'economy.established.logistics': 'Logistique établie',
    'economy.regulatory.advantage': 'Avantage Réglementaire',
    'economy.eu.saf.mandates': 'Mandats SAF UE',
    'economy.carbon.credit.revenue': 'Revenus crédits carbone',
    'economy.france.2030.support': 'Support France 2030',
    'economy.waste.directive.compliance': 'Conformité directive déchets',
    'economy.geographic.benefits': 'Avantages Géographiques',
    'economy.proximity.airports': 'Proximité aéroports',
    'economy.distribution.network': 'Réseau distribution',
    'economy.skilled.workforce': 'Main-d\'œuvre qualifiée',
    'economy.industrial.infrastructure': 'Infrastructure industrielle',
    
    // Economy Tab - Employment & Regional Impact
    'economy.employment.breakdown': 'Impact Emploi Régional',
    'economy.direct.jobs': 'Emplois directs',
    'economy.indirect.jobs': 'Emplois indirects',
    'economy.induced.jobs': 'Emplois induits',
    'economy.total.impact': 'Impact total',
    'economy.ademe.research': 'Basé sur les multiplicateurs d\'emploi ADEME',
    'jobs': 'emplois',
    'economy.regional.impact': 'Impact régional',
    
    // Economy Tab - Financing Overview
    'economy.financing.overview': 'Aperçu du Financement',
    'economy.equity.funding': 'Financement Capitaux Propres',
    'economy.equity.percentage': '35% capitaux propres',
    'economy.bank.debt': 'Dette Bancaire',
    'economy.interest.rate': '4.5% taux d\'intérêt',
    'economy.subsidies': 'Subventions',
    'economy.eu.france.funding': 'UE + France 2030',
    'economy.total.investment': 'Investissement Total',
    'economy.capacity.description': '80kt capacité SAF',
    'economy.scaling.note': 'Modélisation évolutive basée sur la biomasse disponible régionale',
    
    // ROI Calculator - Advanced Features
    'roi.manual.changes.coming': 'Modifications manuelles à venir',
    'roi.atj.technology': 'Technologie ATJ',
    'roi.iata.projections': 'Projections IATA',
    'roi.irena.benchmarks': 'Références IRENA',
    'roi.industry.capex': 'CAPEX Industriel',
    'roi.tonnes.per.year': 'tonnes/an',
    
    // ROI Calculator - Acronym Tooltips
    'roi.irr.french.long': 'TRI - Taux de Rentabilité Interne',
    'roi.irr.english.long': 'TRI - Taux de Rentabilité Interne',
    'roi.irr.explanation.fr': 'Le taux d\'actualisation qui annule la VAN du projet',
    'roi.irr.explanation.en': 'Le taux d\'actualisation qui annule la VAN du projet',
    'roi.npv.french.long': 'VAN - Valeur Actuelle Nette',
    'roi.npv.english.long': 'VAN - Valeur Actuelle Nette',
    'roi.npv.explanation.fr': 'Valeur présente des flux financiers futurs actualisés à 8%',
    'roi.npv.explanation.en': 'Valeur présente des flux financiers futurs actualisés à 8%',
    
    // ROI Calculator - Regional Context
    'roi.champagne.context': 'Paramètres adaptés pour la région viticole premium avec des volumes de biomasse plus faibles mais des produits de plus haute valeur',
    'roi.languedoc.context': 'Paramètres basés sur la disponibilité de déchets vitivinicoles à grande échelle avec une infrastructure agricole établie',
    
    // Biomass Types & Resources
    'types.biomasse': 'Types de Biomasse',
    'marc.raisin': 'Marc de raisin',
    'sous.produits.liquides': 'Sous-produits liquides',
    'bois.taille': 'Bois de taille',
    'sarments': 'Sarments',
    'rafles': 'Rafles',
    'lies': 'Lies',
    'autre.biomasse': 'Autre biomasse',
    'ressources.disponibles': 'Ressources Disponibles',
    
    // Flow Allocation & Supply Strategy
    'strategie.approvisionnement': 'Stratégie d\'Approvisionnement',
    'flux.biomasse': 'Flux de Biomasse',
    'flux.proteges': 'Flux Protégés',
    'flux.negociables': 'Flux Négociables', 
    'flux.disponibles': 'Flux Disponibles',
    'allocation.conservative': 'Base Conservative',
    'potentiel.negociable': 'Potentiel Négociable',
    'disponibilite.immediate': 'Disponibilité Immédiate',
    
    // Infrastructure
    'infrastructure.title': 'Infrastructure Existante',
    'infrastructure.subtitle': 'Installations de valorisation en place',
    'infrastructure.distilleries': 'Distilleries',
    'infrastructure.methanisation': 'Sites de Méthanisation',
    'infrastructure.compostage': 'Installations de Compostage',
    'infrastructure.biomasse': 'Centrales Biomasse',
    'infrastructure.total': 'Total des installations',
    'infrastructure.co2.evite': 'CO₂ évité annuellement',
    'infrastructure.capacite': 'Capacité existante',
    
    // Seasonal & Timeline
    'disponibilite.saisonniere': 'Disponibilité Saisonnière',
    'calendrier.recolte': 'Calendrier de Récolte',
    'planning': 'Planning',
    'maintenance': 'Maintenance',
    'formation': 'Formation',
    'vendanges': 'Vendanges',
    'taille': 'Taille',
    'recolte': 'Récolte',
    'vue.lineaire': 'Vue Linéaire',
    'vue.circulaire': 'Vue Circulaire',
    'legende.intensite': 'Légende intensité',
    'intensite.peak': 'Peak',
    'intensite.eleve': 'Élevé',
    'intensite.moyen': 'Moyen',
    'intensite.faible': 'Faible',
    
    // Months
    'mois.janvier': 'Janvier',
    'mois.fevrier': 'Février',
    'mois.mars': 'Mars',
    'mois.avril': 'Avril',
    'mois.mai': 'Mai',
    'mois.juin': 'Juin',
    'mois.juillet': 'Juillet',
    'mois.aout': 'Août',
    'mois.septembre': 'Septembre',
    'mois.octobre': 'Octobre',
    'mois.novembre': 'Novembre',
    'mois.decembre': 'Décembre',
    
    // Valorization Methods
    'valorisation.title': 'Méthodes de Valorisation',
    'valorisation.distillation': 'Distillation',
    'valorisation.compostage': 'Compostage',
    'valorisation.methanisation': 'Méthanisation',
    'valorisation.epandage': 'Épandage',
    'valorisation.saf': 'Carburant Aviation Durable',
    'valorisation.distillation.desc': 'Transformation en alcool et spiritueux',
    'valorisation.compostage.desc': 'Production d\'amendements organiques',
    'valorisation.methanisation.desc': 'Production de biogaz et digestat',
    'valorisation.epandage.desc': 'Amendement direct des sols',
    'valorisation.saf.desc': 'Production de biocarburant aviation',
    'valorisation.chaines.etablies': 'Chaînes de valorisation établies',
    'valorisation.opportunite.saf': 'Opportunité SAF (30%)',
    'valorisation.conformite': 'Conformité directive déchets UE',
    'valorisation.impact.economique': 'Impact économique régional',
    'valorisation.emplois.crees': 'Emplois créés',
    'valorisation.contexte.regional': 'Contexte régional',
    'valorisation.methodologie': 'Méthodologie basée sur les données sectorielles 2023',
    
    // Industry News & Players
    'actualites.secteur': 'Actualités du Secteur',
    'acteurs.industriels': 'Acteurs Industriels',
    'entreprise.bioenergie': 'Bioénergie Avancée',
    'entreprise.bioenergie.desc': 'Production de biocarburants de 2ème génération à partir de déchets vitivinicoles',
    'entreprise.valorisation': 'Valorisation Verte',
    'entreprise.valorisation.desc': 'Spécialiste du traitement et de la valorisation des sous-produits agricoles',
    'entreprise.innovation': 'Innovation SAF',
    'entreprise.innovation.desc': 'Développement de technologies de conversion biomasse-carburant',
    'statut.certifie': 'Certifié',
    'statut.en.cours': 'En cours',
    'statut.planifie': 'Planifié',
    'feedstock': 'Matière première',
    'certification': 'Certification',
    'biomass.to.liquids': 'Biomasse vers liquides',
    'partenariat.recherche': 'Partenariat de recherche',
    'projet.demonstration': 'Projet de démonstration',
    'investissement.prevu': 'Investissement prévu',
    'emplois.potentiels': 'Emplois potentiels',
    'debut.production': 'Début de production',
    
    // Economic Terms
    'cout.tonne': 'Coût par tonne',
    'prix.marche': 'Prix du marché',
    'retour.investissement': 'Retour sur investissement',
    'benefice.annuel': 'Bénéfice annuel',
    'cout.transport': 'Coût transport',
    'cout.transformation': 'Coût transformation',
    'revenus.potentiels': 'Revenus potentiels',
    'marge.beneficiaire': 'Marge bénéficiaire',
    
    // Partnerships & Collaboration - COMPLETE UPDATE
    'opportunites.partenariat': 'Opportunités de Partenariat',
    'collaboration.recherche': 'Collaboration Recherche',
    'financement.disponible': 'Financement Disponible',
    'subventions.europeennes': 'Subventions Européennes',
    'aides.regionales': 'Aides Régionales',
    
    // Core Partnership Keys - UPDATED
    'partnerships.title': 'Partenariats Stratégiques',
    'partnerships.subtitle': 'Écosystème collaboratif pour la valorisation des déchets vitivinicoles en carburant aviation durable',
    'partnerships.strategic.partnerships': 'Partenariats Stratégiques',
    'partnerships.header.subtitle': 'Écosystème collaboratif pour la valorisation des déchets vitivinicoles en carburant aviation durable de la région',
    'partnerships.opportunities.title': 'Opportunités de Partenariat',
    'partnerships.collaborative.ecosystem': 'Écosystème collaboratif pour le développement SAF',
    'partnerships.note.title': 'Note',
    'partnerships.framework.note': 'Cette analyse s\'appuie sur les retours d\'expérience des projets Neste (Finlande), BP Bunge (Brésil) et Total Energies (France)',
    'partnerships.types.needed': 'Types de Partenariats',
    'partnerships.main.types': 'Types principaux',
    'partnerships.target.partners': 'Partenaires Cibles',
    'partnerships.network.objective': 'Objectif réseau',
    'partnerships.cost.reduction': 'Réduction Coûts',
    'partnerships.waste.treatment': 'Traitement déchets',
    'partnerships.new.revenues': 'Nouveaux Revenus',
    'partnerships.annual.potential': 'Potentiel annuel',
    'partnerships.waste.to.revenue': 'Transformer les coûts de déchets en flux de revenus',
    
    // Partnership Categories - COMPLETE UPDATE
    'partnerships.collectivites.title': 'Collectivités',
    'partnerships.collectivites.desc': 'Partenariats avec les collectivités locales pour la gestion coordonnée des déchets',
    'partnerships.producers.title': 'Producteurs Viticoles',
    'partnerships.waste.available': 'déchets disponibles',
    'partnerships.producers.desc': 'Partenariat avec les producteurs viticoles pour sécuriser l\'approvisionnement en déchets vitivinicoles',
    'partnerships.industrial.title': 'Partenaires Industriels',
    'partnerships.industrial.desc': 'Entreprises avec infrastructure de traitement existante',
    'partnerships.institutional.title': 'Partenaires Institutionnels',
    'partnerships.institutional.desc': 'Organismes publics et centres de recherche',
    'partnerships.saf.companies.title': 'Entreprises SAF',
    'partnerships.feedstock.demand': 'Demande croissante de matières premières',
    'partnerships.saf.companies.desc': 'Collaboration avec les producteurs de carburant aviation durable pour répondre à la demande croissante',
    'partnerships.tourism.title': 'Opérateurs Touristiques',
    'partnerships.sustainability.story': 'Récit de durabilité',
    'partnerships.tourism.desc': 'Valorisation de l\'image durable auprès des opérateurs touristiques et compagnies aériennes',
    'partnerships.regional.government.title': 'Gouvernement Régional',
    'partnerships.circular.economy': 'Soutien économie circulaire',
    'partnerships.regional.government.desc': 'Accompagnement public pour développer l\'économie circulaire et les filières durables',
    
    // Benefits - COMPLETE UPDATE
    'partnerships.benefits.waste.reduction': 'Réduction des déchets',
    'partnerships.benefits.local.revenue': 'Revenus locaux',
    'partnerships.benefits.job.creation': 'Créations d\'emplois',
    'partnerships.benefits.carbon.goals': 'Objectifs carbone',
    'partnerships.benefits.waste.valorization': 'Valorisation déchets',
    'partnerships.benefits.additional.income': 'Revenus additionnels',
    'partnerships.benefits.sustainability': 'Durabilité',
    'partnerships.benefits.cost.reduction': 'Réduction coûts',
    'partnerships.benefits.existing.infrastructure': 'Infrastructure existante',
    'partnerships.benefits.optimized.logistics': 'Logistique optimisée',
    'partnerships.benefits.technical.expertise': 'Expertise technique',
    'partnerships.benefits.economies.scale': 'Économies d\'échelle',
    'partnerships.benefits.regulatory.support': 'Support réglementaire',
    'partnerships.benefits.financement.public': 'Financement public',
    'partnerships.benefits.validation.scientifique': 'Validation scientifique',
    'partnerships.benefits.reseau.institutionnel': 'Réseau institutionnel',
    'partnerships.benefits.waste.elimination': 'Élimination des déchets',
    'partnerships.benefits.additional.revenue': 'Revenus additionnels',
    'partnerships.benefits.sustainable.image': 'Image durable',
    'partnerships.benefits.secure.feedstock': 'Approvisionnement sécurisé',
    'partnerships.benefits.production.scale': 'Montée en production',
    'partnerships.benefits.regulatory.compliance': 'Conformité réglementaire',
    'partnerships.benefits.green.branding': 'Image verte',
    'partnerships.benefits.customer.engagement': 'Engagement client',
    'partnerships.benefits.marketing.differentiation': 'Différenciation marketing',
    
    // Industry Examples & Table - COMPLETE UPDATE
    'partnerships.neste.model': 'Modèle Neste',
    'partnerships.neste.desc': 'Partenariats décentralisés avec collecteurs locaux',
    'partnerships.bp.model': 'Modèle BP Bunge',
    'partnerships.bp.desc': 'Intégration verticale avec producteurs agricoles',
    'partnerships.total.model': 'Modèle Total Energies',
    'partnerships.total.desc': 'Approche collaborative multi-partenaires',
    'partnerships.feedstock.food.waste': 'Déchets alimentaires',
    'partnerships.feedstock.agricultural.residues': 'Résidus agricoles',
    'partnerships.feedstock.mixed.biomass': 'Biomasse mixte',
    'partnerships.tonnes.year': 'tonnes/an',
    'partnerships.tonnes.saf.year': 'tonnes SAF/an',
    'partnerships.table.model': 'Modèle',
    'partnerships.table.description': 'Description',
    'partnerships.table.partners': 'Partenaires',
    'partnerships.table.feedstock': 'Matière Première',
    'partnerships.table.capacity': 'Capacité',
    'partnerships.partnership.total': 'Partenariat Total Energies',
    'partnerships.ethanol.agricultural.waste': 'Éthanol de déchets agricoles',
    'partnerships.certified': 'approuvée',
    'partnerships.green.fuels': 'Carburants Verts',
    'partnerships.mobilized': 'mobilisé',
    'partnerships.hydrogen.aircraft.2035': 'Avion hydrogène 2035',
    'partnerships.french.airports.equipped': 'aéroports français équipés',
    'partnerships.saf.strategy.france.2030': 'Stratégie SAF France 2030',
    'partnerships.over.5.years': 'sur 5 ans',
    'partnerships.tonnes.saf.year.capacity': 'tonnes SAF/an capacité',
    'partnerships.biorefineries.modernized': 'bioraffineries modernisées',
    'partnerships.biomass.suppliers': 'fournisseurs biomasse',
    'partnerships.investment': 'Investissement',
    'partnerships.capacity': 'Capacité',
    'partnerships.technology': 'Technologie',
    'partnerships.partnership': 'Partenariat',
    
    // Implementation & Phases - COMPLETE
    'partnerships.progressive.approach': 'Approche progressive basée sur les meilleures pratiques sectorielles',
    'partnerships.phase': 'Phase',
    'partnerships.duration': 'Durée',
    'partnerships.partners': 'Partenaires',
    'partnerships.target.volume': 'Volume cible',
    'partnerships.tonnes': 'tonnes',
    
    // Existing Phase Keys
    'partnerships.phase.pilot': 'Phase Pilote',
    'partnerships.phase.pilot.desc': 'Validation technique et économique',
    'partnerships.phase.scale': 'Phase d\'Expansion',
    'partnerships.phase.scale.desc': 'Montée en échelle progressive',
    'partnerships.phase.mature': 'Phase Mature',
    'partnerships.phase.mature.desc': 'Optimisation et expansion régionale',
    
    // Value Proposition & Final - COMPLETE
    'partnerships.transform.costs.to.revenue': 'Transformation des coûts de déchets en flux de revenus',
    'partnerships.per.tonne': 'par tonne',
    'partnerships.implementation.planning': 'Planification Mise en Œuvre',
    'partnerships.roadmap.key.steps': 'Roadmap et étapes clés du projet',
    'partnerships.methodology.title': 'Méthodologie',
    'partnerships.methodology.note': 'Note Méthodologique',
    'partnerships.strategic.regional.saf': 'Partenariats stratégiques pour une filière SAF régionale',
    
    // Existing Partnership Keys
    'partnerships.value.proposition': 'Proposition de Valeur',
    'partnerships.current.costs': 'Coûts Actuels',
    'partnerships.waste.disposal': 'Élimination déchets',
    'partnerships.transport.costs': 'Coûts transport',
    'partnerships.saf.revenue': 'Revenus SAF',
    'partnerships.carbon.credits': 'Crédits carbone',
    'partnerships.net.benefit': 'Bénéfice net',
    'partnerships.implementation.phases': 'Phases de Mise en Œuvre',
    'partnerships.industry.examples': 'Exemples Industriels',
    'partnerships.examples.subtitle': 'Modèles de partenariats observés dans l\'industrie',
    'partnerships.framework.disclaimer': 'Cadre d\'analyse basé sur les données sectorielles',
    'timeline.months': 'mois',
    
    // Legacy Partnership Keys
    'partenariats.requis': 'Types de Partenariats Requis',
    'types.principaux': 'Types principaux',
    'partenaires.cibles': 'Partenaires Cibles',
    'objectif.reseau': 'Objectif réseau',
    'reduction.couts': 'Réduction Coûts',
    'traitement.dechets': 'Traitement déchets',
    'nouveaux.revenus': 'Nouveaux Revenus',
    'potentiel.annuel': 'Potentiel annuel',
    'phases.implementation': 'Phases de Mise en Œuvre',
    'approche.progressive': 'Approche progressive basée sur les meilleures pratiques sectorielles',
    'duree': 'Durée',
    'partenaires': 'Partenaires',
    'volume.cible': 'Volume cible',
    'proposition.valeur': 'Proposition de Valeur',
    'transformation.couts': 'Transformation des coûts de déchets en flux de revenus',
    'benefice.net.tonne': 'Bénéfice net par tonne',
    'planification.oeuvre': 'Planification Mise en Œuvre',
    'roadmap.etapes': 'Roadmap et étapes clés du projet',
    'timeline.implementation': 'Timeline d\'Implémentation',
    
    // Project Phases
    'etude.faisabilite': 'Étude de Faisabilité',
    'developpement.partenariats': 'Développement Partenariats',
    'financement.autorisations': 'Financement et Autorisations',
    'construction.infrastructure': 'Construction Infrastructure',
    'demarrage.production': 'Démarrage Production',
    'expansion.regionale': 'Expansion Régionale',
    
    // Phase Status
    'termine': 'Terminé',
    'en.cours': 'En cours',
    'planifie': 'Planifié',
    'progression': 'Progression',
    'jalons': 'Jalons',
    
    // Phase Details
    'analyse.complete': 'Analyse technique et économique complète du projet',
    'etude.marche': 'Étude de marché',
    'analyse.technique': 'Analyse technique',
    'modele.economique': 'Modèle économique',
    'rapport.final': 'Rapport final',
    
    // Stakeholders
    'parties.prenantes': 'Parties Prenantes',
    'equipe.projet': 'Équipe projet',
    'consultants.externes': 'Consultants externes',
    'investisseurs': 'Investisseurs',
    'dependances': 'Dépendances',
    'aucune.dependance': 'Aucune dépendance',
    'risques.identifies': 'Risques Identifiés',
    'delais.consultants': 'Délais consultants',
    'evolution.reglementaire': 'Évolution réglementaire',
    
    // Project Summary
    'resume.global.projet': 'Résumé Global du Projet',
    'phases.terminees': 'Phases terminées',
    'phases.en.cours': 'Phases en cours',
    'progression.totale': 'Progression totale',
    'mois.estimes': 'Mois estimés',
    
    // Methodology & Data
    'methodologie.title': 'Méthodologie',
    'sources.donnees': 'Sources de Données',
    'collecte.donnees': 'Collecte de Données',
    'validation.donnees': 'Validation des Données',
    'mise.jour.donnees': 'Mise à jour des données',
    'references.scientifiques': 'Références Scientifiques',
    'hypotheses.calcul': 'Hypothèses de Calcul',
    'limites.etude': 'Limites de l\'Étude',
    
    // Contact & Support
    'contact.title': 'Contact',
    'support.technique': 'Support Technique',
    'informations.projet': 'Informations Projet',
    'demande.donnees': 'Demande de Données',
    'collaboration.industrie': 'Collaboration Industrie',
    
    // Debug & System
    'debug.mode': 'Mode Debug',
    'debug.donnees.region': 'Données région',
    'debug.traductions.manquantes': 'Traductions manquantes',
    'debug.validation.donnees': 'Validation des données',
    'erreur.chargement': 'Erreur de chargement',
    'donnees.non.disponibles': 'Données non disponibles',
    
    // Units & Measurements - COMPLETE WITH ALL UNIT KEYS
    'unite.tonnes': 'tonnes',
    'unite.hectares': 'ha',
    'unite.pourcentage': '%',
    'unite.euros': '€',
    'unite.emplois': 'emplois',
    'unite.annee': '/an',
    'unite.kilogrammes': 'kg',
    'unite.litres': 'L',
    'units.tonne': 'tonne',
    'units.tonnes': 'tonnes',
    'litres.an': 'litres/an',
    
    // Cost-Benefit Analysis & Economic Projections Units
    'currency.euro': '€',
    'units.million': 'M',
    'units.kilotonnes': 'kt',
    'units.kilo': 'k',
    'units.percent': '%',
    'common.plus': '+',
    'common.year': 'an',
    'units.kilograms': 'kg',
    'units.liters': 'L',
    'units.liter': 'L',
    'units.tonnes': 't',
    'units.tonne': 't',
    
    // Resources Tab - COST BENEFIT ANALYSIS (NEW KEYS)
    'cost.benefit.title': 'Analyse Coût-Bénéfice',
    'cost.benefit.comparison': 'Comparaison',
    'cost.benefit.timeline': 'Chronologie',
    'cost.benefit.breakdown': 'Répartition',
    'cost.benefit.profit.improvement': 'Amélioration profit',
    'cost.benefit.additional.benefit': 'Bénéfice additionnel',
    'cost.benefit.jobs.created': 'Emplois créés',
    'cost.benefit.co2.avoided.annual': 'CO₂ évité annuel',
    'cost.benefit.real.data': 'Données Réelles',
    'cost.benefit.revenue': 'Revenus',
    'cost.benefit.operating.costs': 'Coûts opérationnels',
    'cost.benefit.net.profit': 'Profit net',
    'cost.benefit.traditional.valorization': 'Valorisation traditionnelle',
    'cost.benefit.saf.valorization': 'Valorisation SAF',
    'cost.benefit.detailed.comparison': 'Comparaison Détaillée',
    'cost.benefit.category': 'Catégorie',
    'cost.benefit.traditional': 'Traditionnel',
    'cost.benefit.saf': 'SAF',
    'cost.benefit.difference': 'Différence',
    'cost.benefit.improvement': 'Amélioration',
    'cost.benefit.context': 'Contexte',
    'cost.benefit.languedoc.context': 'Analyse basée sur les capacités industrielles et l\'infrastructure logistique établie de la plus grande région viticole française',
    
    // Economy Tab - FINANCING OVERVIEW (NEW KEYS)
    'economy.financing.overview': 'Aperçu du Financement',
    'economy.equity.funding': 'Financement Capitaux Propres',
    'economy.equity.percentage': '35% capitaux propres',
    'economy.bank.debt': 'Dette Bancaire',
    'economy.interest.rate': '4.5% taux d\'intérêt',
    'economy.subsidies': 'Subventions',
    'economy.eu.france.funding': 'UE + France 2030',
    'economy.total.investment': 'Investissement Total',
    'economy.capacity.description': '80kt capacité SAF',
    'economy.scaling.note': 'Modélisation évolutive basée sur la biomasse disponible régionale',
    
    // Common Actions
    'voir.details': 'Voir détails',
    'telecharger': 'Télécharger',
    'exporter.donnees': 'Exporter données',
    'imprimer.rapport': 'Imprimer rapport',
    'partager.lien': 'Partager lien',
    'copier.lien': 'Copier lien',
    'fermer': 'Fermer',
    'ouvrir': 'Ouvrir',
    'suivant': 'Suivant',
    'precedent': 'Précédent',
    'retour': 'Retour',
    'accueil': 'Accueil'
  },
  en: {
    // Main Atlas Headers
    'atlas.title': 'Viticulture Biomass Atlas',
    'region.subtitle': 'Potential for sustainable aviation fuel valorization',
    
    // Navigation & Interface
    'visite.guidee': 'Guided Tour',
    'donnees.certifiees': 'Certified Data 2023',
    'mode.presentation': 'Presentation Mode',
    'partager': 'Share',
    'imprimer': 'Print',
    
    // Navigation & Header - EXPANDED
    'header.title': 'SAF {region}',
    'header.subtitle': 'Valorization of viticulture waste into sustainable aviation fuel',
    'nav.vue.ensemble': 'Overview',
    'nav.economie': 'Economics',
    'nav.ressources': 'Resources',
    'nav.partenaires': 'Partners',
    'nav.donnees': 'Data',
    'nav.methodologie': 'Methodology',
    'nav.contact': 'Contact',
    'nav.overview.description': 'Regional statistics and key metrics',
    'nav.resources.description': 'Available resource analysis',
    'nav.economy.description': 'Economic tools and calculators',
    'nav.partnerships.description': 'Collaborative opportunities',
    'nav.methodology.description': 'Methodology and data sources',
    'nav.contact.description': 'Contact information and support',
    
    // Regional Data & Statistics
    'region.current': 'Current Region',
    'donnees.regionales': 'Regional Data',
    'surface.viticole': 'Viticulture Surface',
    'production.annuelle': 'Annual Production',
    'production.waste': 'Annual viticulture waste production',
    'production.total.biomass': 'Total biomass production',
    'production.marc': 'Annual pomace production',
    'production.regionale': 'Regional Production',
    'repartition.departementale': 'Departmental Distribution',
    'repartition.production.commune': 'Production Distribution by Commune',
    'communes.principales': 'Main Producing Communes',
    'disponible': 'Available',
    'jusqua': 'Up to',
    
    // Overview Tab - COMPLETE ENGLISH WITH NEW BANNER & MARKET VALIDATION
    'points.cles': 'Key Points',
    'points.cles.subtitle': 'Regional performance indicators',
    'superficie.viticole': 'Wine-growing Area',
    'base.regionale': 'Regional Base',
    'production.dechets.vitivinicoles': 'Viticulture waste production',
    'matiere.premiere.totale': 'Total feedstock',
    'allocation.flux': 'Flow allocation',
    'disponible.saf': 'Available SAF',
    'potentiel.saf': 'SAF potential',
    'revenue.potential': 'Revenue potential',
    'reduction.co2.potential': 'Potential CO₂ reduction',
    'vs.fossile': 'vs fossil',
    'co2.calculation.tooltip': '15.7M liters SAF × 2.5kg CO₂/liter avoided vs fossil fuel',
    'analyse.regionale': 'Regional Analysis',
    'analyse.regionale.subtitle': 'Distribution and potential by geographic area',
    'production.regionale.percent': 'Regional Production',
    'saf.potential': 'SAF Potential',
    'base.sur.disponibles': 'Based on 80k tonnes available',
    
    // Banner & Transformation Section
    'banner.transform.title': 'Transform Viticulture Waste into SAF',
    'banner.waste.regional': 'regional waste',
    'banner.valorizable': 'valorizable',
    'banner.respects.existing': 'Respects existing supply chains',
    
    // Market Validation - IATA Section  
    'market.validation.title': 'International Market Validation',
    'market.validation.subtitle': 'Latest IATA data confirms strategic opportunity',
    'iata.report.title': 'IATA Global Feedstock Assessment 2025',
    'iata.report.subtitle': 'Validation of Agricultural Residues Strategy',
    'iata.deficit.saf': 'SAF Deficit',
    'iata.deficit.desc': '100 Mt shortage by 2050',
    'iata.agricultural.residues': 'Agricultural Residues',
    'iata.agricultural.desc': '58% of priority feedstocks',
    'iata.europe': 'Europe',
    'iata.europe.desc': 'Top 4 globally for development',
    'iata.etj.technology': 'EtJ Technology',
    'iata.etj.desc': 'Validated pathway for agricultural materials',
    'iata.source': 'Source: IATA Global Feedstock Assessment for SAF Production Outlook to 2050 - January 2025',
    
    // Market Opportunity
    'market.opportunity.title': 'Market Opportunity',
    'market.demand.2050': 'SAF Demand 2050',
    'market.production.forecast': 'Forecasted production',
    'market.deficit.gap': 'DEFICIT TO BRIDGE',
    
    // Regional Implementation
    'regional.implementation.title': 'Regional Implementation',
    'regional.implementation.subtitle': 'Existing infrastructure and respectful biomass strategy',
    'regional.advantages.title': 'Regional Competitive Advantages',
    'regional.advantages.subtitle': 'Mature infrastructure and French viticulture leadership',
    
    // Industry Momentum
    'industry.momentum.title': 'Industry Momentum',
    'industry.momentum.subtitle': 'Reference projects and regulatory support',
    'industry.reference.projects': 'Reference Projects',
    'industry.major.industrials': 'Major Industrials',
    'industry.airbus.program.desc': 'Hydrogen aircraft 2035 • 10% SAF minimum 2030 • €15B R&D',
    'industry.total.strategy.desc': '€500M over 5 years • 1.5M t SAF/year • 6 modernized biorefineries',
    'industry.regulatory.support': 'Regulatory Support',
    'regulatory.saf.minimum': '2% SAF minimum 2025 (EU)',
    'regulatory.france.2030': 'France 2030',
    'regulatory.eu.repower': 'EU REPowerEU',
    'regulatory.carbon.neutral': 'Carbon neutrality',
    
    // Call-to-Action Section
    'cta.strategic.opportunity': 'A Strategic Opportunity to Seize',
    'cta.transform.challenge': 'Transform viticulture waste challenge into SAF competitive advantage',
    'cta.timing.optimal': 'Optimal Timing',
    'cta.timing.desc': 'Favorable regulation + growing demand',
    'cta.first.mover': 'First-Mover',
    'cta.first.mover.desc': 'Constraint = deployment, not resources',
    'cta.win.win': 'Win-Win',
    'cta.win.win.desc': 'Respects supply chains + creates value',
    
    // Overview Tab Metrics - ENGLISH RESTORED
    'metriques.cles': 'Key Metrics',
    'hectares': 'hectares',
    'tonnes.annee': 'tonnes/year',
    'producteurs': 'producers',
    'communes': 'communes',
    'communes.tracked': 'Communes tracked',
    'communes.total.production': 'Total commune production',
    'communes.coverage': 'Commune coverage',
    'communes.methodology.note': 'Methodology based on 2023 departmental data',
    'industries.cles': 'Key Industries',
    'cooperatives': 'Cooperatives',
    'distilleries': 'Distilleries',
    'sites.methanisation': 'Methanization Sites',
    'installations.compostage': 'Composting Facilities',
    
    // Resources Tab - ENGLISH RESTORED ALL MISSING KEYS
    'resources.title': 'Available Resources',
    'resources.subtitle': 'Detailed analysis of biomass flows and infrastructure',
    'resources.allocationTitle': 'Flow Allocation Strategy',
    'resources.allocationSubtitle': 'Distribution of 266,000 tonnes of biomass by destination',
    'resources.total.biomass.regional': 'Total regional biomass',
    'non.disponible': 'Not available',
    'compost.vignobles': 'Vineyard compost',
    'biogaz.energetique': 'Energy biogas',
    'extraction.premium': 'Premium extraction',
    'surplus.excedents': 'Surplus excess',
    'excedent.compost': 'Compost excess',
    'couts.elimination': 'Disposal costs',
    'boues.traitement': 'Treatment sludge',
    'repartition.detaillee.biomasse': 'Detailed Biomass Distribution',
    'tonnage.total': 'Total tonnage',
    'part.total': 'Total share',
    'communes.impliquees': 'Communes involved',
    
    // Infrastructure - ENGLISH RESTORED MISSING KEYS
    'infrastructure.methanization': 'Methanization',
    'infrastructure.composting': 'Composting',
    'infrastructure.biomass': 'Biomass',
    'co2.evite.annuel': 'Annual CO₂ avoided',
    'infrastructure.co2.calculation.tooltip': 'Estimate: 27 methanization (×2.1kt) + 26 composting (×0.8kt) + 4 biomass (×5kt)',
    'infrastructure.total.facilities': 'Total facilities',
    'infrastructure.existing.capacity': 'Existing capacity',
    'infrastructure.disclaimer': 'Methodology based on 2023 sectoral data',
    
    // Seasonal Timeline - ENGLISH RESTORED INTENSITY LEVELS
    'peak': 'Peak',
    'eleve': 'High',
    'moyen': 'Medium',
    'faible': 'Low',
    'preparation': 'Preparation',
    'contrats': 'Contracts',
    'veille': 'Monitoring',
    'optimisation': 'Optimization',
    'tests': 'Testing',
    'mobilisation': 'Mobilization',
    'coordination': 'Coordination',
    'stockage': 'Storage',
    'bilan': 'Assessment',
    'planification': 'Planning',
    
    // Valorization - ENGLISH RESTORED MISSING KEYS
    'valorization.title': 'Current Valorization Methods',
    'valorization.subtitle': 'Biomass flow distribution by sector',
    'valorization.breakdown': 'Valorization breakdown',
    'valorization.distillation': 'Distillation',
    'valorization.distillation.desc': 'Alcohol and spirits production',
    'valorization.composting': 'Composting',
    'valorization.composting.desc': 'Organic amendments',
    'valorization.methanization': 'Methanization',
    'valorization.methanization.desc': 'Biogas and digestate production',
    'valorization.direct.spreading': 'Direct spreading',
    'valorization.spreading.desc': 'Direct soil amendment',
    'valorization.regional.context': 'Regional Context',
    'valorization.established.chains': 'Established chains',
    'valorization.mature.infrastructure': 'Mature infrastructure',
    'valorization.saf.opportunity': 'SAF opportunity',
    'valorization.new.allocation': 'New allocation',
    'valorization.compliance': 'Compliance',
    'valorization.eu.directive': 'EU waste directive',
    'valorization.economic.impact': 'Economic impact',
    'valorization.jobs.supported': 'jobs supported',
    'valorization.methodology.note': 'Methodology based on 2023 sectoral data',
    
    // Strategy & Context - ENGLISH RESTORED
    'strategie.biomasse': 'Biomass Strategy',
    'base.conservative': 'Conservative base',
    'flux.elimination': 'Disposal flows',
    'surplus.excedents': 'Surplus excess',
    'total.accessible': 'Total accessible',
    'avec.partenariats': 'With partnerships',
    'respecte.filieres': 'Respects existing channels',
    'contexte.regional': 'Regional Context',
    'contexte.regional.subtitle': 'Strategic position in the French wine ecosystem',
    'region.viticole.francaise': 'French wine region',
    'volume.production': 'Production volume',
    'production.nationale': 'National production',
    'millions': 'million',
    'ca.annuel': 'Annual revenue',
    'secteur.vitivinicole': 'Wine sector',
    
    // Industry News - ENGLISH RESTORED ALL KEYS  
    'actualites.saf': 'SAF News',
    'actualites.subtitle': 'Recent developments in the industry',
    'industry.haffner.title': 'Haffner Energy',
    'industry.haffner.subtitle': 'First large-scale SAF project in France',
    'investissement': 'Investment',
    'capacite': 'Capacity',
    'tonnes.saf.an': 'tonnes SAF/year',
    'des.2025': 'from 2025',
    'technologie': 'Technology',
    'partenariat': 'Partnership',
    'industry.lanzajet.title': 'LanzaJet',
    'industry.lanzajet.subtitle': 'First commercial SAF refinery in the United States',
    'industry.lanzajet.first.commercial': 'First commercial refinery',
    'waste.agricultural.ethanol': 'Agricultural ethanol and waste',
    'industry.airbus.title': 'Airbus',
    'industry.airbus.subtitle': 'Ambitious goals for green aviation',
    'industry.airbus.hydrogen.objective': '100% hydrogen 2035',
    'industry.airbus.saf.transition': 'SAF transition',
    'minimum.2030': 'Minimum 2030',
    'industry.airbus.partnerships': 'Airport partnerships',
    'industry.airbus.airports': 'European airports',
    'budget.rd': 'R&D budget',
    'milliards': 'billion',
    'mobilises': 'mobilized',
    'industry.total.title': 'Total Energies',
    'industry.total.subtitle': 'Integrated biofuel strategy',
    'sur.ans': 'Over 5 years',
    'objectif': 'Objective',
    'industry.total.biorefineries': 'Biorefineries',
    'industry.total.sites.modernized': '6 modernized sites',
    'industry.total.partnerships': 'Partnerships',
    'industry.total.biomass.suppliers': 'Biomass suppliers',
    
    // Regulatory Context - ENGLISH RESTORED
    'contexte.reglementaire': 'Regulatory Context',
    'fonds.verts': 'Green funds',
    'energies.renouvelables': 'Renewable energy',
    'neutralite.carbone': 'Carbon neutrality 2050',
    'projet.inscrit': 'Project integrated into national strategy',
    
    // Footer & Methodology - ENGLISH RESTORED ALL KEYS
    'footer.project.description': 'Valorization of viticulture waste into sustainable aviation fuel',
    'footer.revenues': 'Potential revenues',
    'footer.co2.avoided': 'CO₂ avoided',
    'footer.methodology.standards': 'Methodological Standards',
    'methodology.atj.title': 'ATJ Technology',
    'methodology.atj.description': 'Alcohol-to-Jet certified ASTM D7566',
    'methodology.agreste.title': 'Agreste Data',
    'methodology.agreste.description': 'Official agricultural statistics',
    'methodology.ifv.title': 'IFV Institute',
    'methodology.ifv.description': 'French viticulture research',
    'methodology.corsia.title': 'CORSIA Standards',
    'methodology.corsia.description': 'International ICAO validation',
    'footer.certifications.audits': 'Certifications and Audits',
    'credentials.bureau.veritas': 'Bureau Veritas verification',
    'credentials.astm.compliance': 'ASTM D7566 compliance',
    'credentials.corsia.validation': 'CORSIA validation',
    'credentials.quarterly.audit': 'Quarterly audit',
    'credentials.peer.reviewed': 'Peer reviewed',
    'footer.institutional.partners': 'Institutional Partners',
    'partners.region.occitanie': 'Occitanie Region',
    'partners.ifv': 'French Institute of Vine',
    'partners.safer.languedoc': 'SAFER Languedoc',
    'partners.chamber.herault': 'Hérault Agriculture Chamber',
    'partners.vignerons.union': 'Winegrowers Union',
    'footer.primary.data.sources': 'Primary Data Sources',
    'data.sources.agreste': 'Agreste Statistics',
    'data.sources.ifv': 'IFV Research',
    'data.sources.oiv': 'International Wine Organization',
    'data.sources.aviation.fuel': 'Aviation Fuel Analytics',
    'footer.scientific.validation': 'Scientific Validation',
    'validation.peer.review': 'Peer review',
    'validation.bureau.veritas': 'Bureau Veritas audit',
    'validation.iso.compliance': 'ISO compliance',
    'validation.carbon.audit': 'Carbon audit',
    'footer.international.standards': 'International Standards',
    'standards.astm.d7566': 'ASTM D7566',
    'standards.corsia.icao': 'CORSIA ICAO',
    'standards.red.ii': 'RED II',
    'standards.iscc.eu': 'ISCC EU',
    
    // Economy Tab - COMPLETE WITH ALL SECTIONS
    'economy.title': 'Economic Analysis',
    'economy.subtitle': 'Financial modeling and investment opportunities',
    'economy.cost.benefit.title': 'Cost-Benefit Analysis',
    'economy.cost.benefit.description': 'Economic comparison between traditional valorization and SAF production',
    'economy.projections.title': 'Economic Projections',
    'economy.projections.description': 'Financial evolution and regional impact over 5-10 years',
    'economy.regional.context': 'Regional economic context',
    'economy.investment.opportunity': 'Investment opportunity',
    'economy.available.feedstock': 'Available feedstock',
    'economy.biomass.secured': 'Secured biomass',
    'economy.feedstock.tooltip': '30% of 266k tonnes total biomass available for SAF',
    'economy.saf.production': 'SAF production',
    'economy.annual.revenue': 'Annual revenue',
    'economy.market.price': 'Market price',
    'economy.jobs.created': 'Jobs created',
    'economy.direct.employment': 'Direct employment',
    'economy.analysis.modules': 'Analysis Modules',
    'economy.financial.modeling': 'Financial Modeling',
    'economy.roi.calculator': 'ROI Calculator',
    'economy.cost.benefit': 'Cost-Benefit',
    'economy.projections': 'Projections',
    'economy.roi.title': 'Advanced ROI Calculator',
    'economy.roi.description': 'Profitability analysis with certified regional data',
    'roi.calculator.title': 'ROI Calculator',
    'roi.real.data': 'Real Data',
    'roi.export': 'Export',
    'roi.conservative': 'Conservative',
    'roi.realistic': 'Realistic',
    'roi.optimistic': 'Optimistic',
    'roi.scenario.parameters': 'Scenario Parameters',
    'roi.biomass.input': 'Biomass input',
    'roi.process.efficiency': 'Process efficiency',
    'roi.saf.price': 'SAF price',
    'roi.operating.costs': 'Operating costs',
    'roi.capital.investment': 'Capital investment',
    'roi.saf.production.annual': 'Annual SAF production',
    'roi.five.year': '5-year ROI',
    'roi.payback.years': 'Payback period',
    'roi.irr': 'IRR',
    'roi.revenue.costs.annual': 'Annual Revenue and Costs',
    'roi.gross.revenue': 'Gross revenue',
    'roi.operating.costs': 'Operating costs',
    'roi.gross.profit': 'Gross profit',
    'roi.financial.indicators': 'Financial Indicators',
    'roi.npv.ten.years': '10-year NPV',
    'roi.gross.margin': 'Gross margin',
    'roi.capital.required': 'Required capital',
    'economy.market.advantage': 'Market Advantage',
    'economy.competitive.positioning': 'Competitive Positioning',
    'economy.feedstock.security': 'Feedstock Security',
    'economy.local.supply.chain': 'Local supply chain',
    'economy.waste.stream.cost': 'Waste stream cost',
    'economy.year.round.availability': 'Year-round availability',
    'economy.established.logistics': 'Established logistics',
    'economy.regulatory.advantage': 'Regulatory Advantage',
    'economy.eu.saf.mandates': 'EU SAF mandates',
    'economy.carbon.credit.revenue': 'Carbon credit revenue',
    'economy.france.2030.support': 'France 2030 support',
    'economy.waste.directive.compliance': 'Waste directive compliance',
    'economy.geographic.benefits': 'Geographic Benefits',
    'economy.proximity.airports': 'Airport proximity',
    'economy.distribution.network': 'Distribution network',
    'economy.skilled.workforce': 'Skilled workforce',
    'economy.industrial.infrastructure': 'Industrial infrastructure',
    
    // Economy Tab - Employment & Regional Impact
    'economy.employment.breakdown': 'Regional Employment Impact',
    'economy.direct.jobs': 'Direct jobs',
    'economy.indirect.jobs': 'Indirect jobs',
    'economy.induced.jobs': 'Induced jobs',
    'economy.total.impact': 'Total impact',
    'economy.ademe.research': 'Based on ADEME employment multipliers',
    'jobs': 'jobs',
    'economy.regional.impact': 'Regional impact',
    
    // Economy Tab - Financing Overview
    'economy.financing.overview': 'Financing Overview',
    'economy.equity.funding': 'Equity Funding',
    'economy.equity.percentage': '35% equity',
    'economy.bank.debt': 'Bank Debt',
    'economy.interest.rate': '4.5% interest rate',
    'economy.subsidies': 'Subsidies',
    'economy.eu.france.funding': 'EU + France 2030',
    'economy.total.investment': 'Total Investment',
    'economy.capacity.description': '80kt SAF capacity',
    'economy.scaling.note': 'Scalable modeling based on regional biomass availability',
    
    // ROI Calculator - Advanced Features
    'roi.manual.changes.coming': 'Manual parameter changes coming soon',
    'roi.atj.technology': 'ATJ Technology',
    'roi.iata.projections': 'IATA Projections',
    'roi.irena.benchmarks': 'IRENA Benchmarks',
    'roi.industry.capex': 'Industry CAPEX',
    'roi.tonnes.per.year': 'tonnes/year',
    
    // ROI Calculator - Acronym Tooltips
    'roi.irr.french.long': 'IRR - Internal Rate of Return',
    'roi.irr.english.long': 'IRR - Internal Rate of Return',
    'roi.irr.explanation.fr': 'The discount rate that makes the project\'s NPV equal to zero',
    'roi.irr.explanation.en': 'The discount rate that makes the project\'s NPV equal to zero',
    'roi.npv.french.long': 'NPV - Net Present Value',
    'roi.npv.english.long': 'NPV - Net Present Value',
    'roi.npv.explanation.fr': 'Present value of future cash flows discounted at 8%',
    'roi.npv.explanation.en': 'Present value of future cash flows discounted at 8%',
    
    // ROI Calculator - Regional Context
    'roi.champagne.context': 'Parameters scaled for premium wine region with smaller biomass volumes but higher value products',
    'roi.languedoc.context': 'Parameters based on large-scale viticulture waste availability with established agricultural infrastructure',
    
    // ADDED: Economic Projections - ALL MISSING KEYS
    'projections.title': 'Regional Economic Projections',
    'projections.five.years': '5 years',
    'projections.ten.years': '10 years',
    'projections.export': 'Export',
    'projections.certified.data': 'Certified Data',
    'projections.official.sources': 'Official Sources',
    'projections.volume': 'Volume',
    'projections.pomace': 'pomace',
    'projections.saf': 'SAF',
    'projections.price': 'Price',
    'projections.co2': 'CO₂',
    'projections.avoided': 'avoided',
    'projections.efficiency': 'Efficiency',
    'projections.cumulative.profit': 'Cumulative profit',
    'projections.total.jobs': 'Total jobs',
    'projections.taxes.collected': 'Taxes collected',
    'projections.co2.avoided.cumulative': 'Cumulative CO₂ avoided',
    'projections.financial.evolution': 'Financial Evolution',
    'projections.years': 'years',
    'projections.revenue': 'Revenue',
    'projections.costs': 'Costs',
    'projections.annual.profit': 'Annual profit',
    'projections.job.creation': 'Job Creation',
    'projections.jobs': 'jobs',
    'projections.annual.carbon.impact': 'Annual Carbon Impact',
    'projections.co2.avoided': 'CO₂ avoided',
    'projections.economic.multipliers': 'Economic Multipliers',
    'projections.oecd.source': 'Source: OECD Rural Development Studies',
    'projections.agriculture': 'Agriculture',
    'projections.industry': 'Industry',
    'projections.services': 'Services',
    'projections.transport': 'Transport',
    'projections.construction': 'Construction',
    'projections.direct': 'Direct',
    'projections.indirect': 'Indirect',
    'projections.total': 'Total',
    'projections.regional.economic.impact': 'Regional Economic Impact',
    'projections.direct.jobs': 'Direct jobs',
    'projections.indirect.jobs': 'Indirect jobs',
    'projections.total.payroll': 'Total payroll',
    'projections.local.purchases': 'Local purchases',
    'projections.tax.contribution': 'Tax contribution',
    'projections.average.salary': 'Average salary',
    'projections.context': 'Context',
    'projections.champagne.context': 'Modeling adapted to the premium market with lower volumes but higher valorization thanks to regional prestige',
    'projections.languedoc.context': 'Projections based on industrial scale and established logistics infrastructure of France\'s largest wine region',
    
    // Biomass Types & Resources
    'types.biomasse': 'Biomass Types',
    'marc.raisin': 'Grape pomace',
    'sous.produits.liquides': 'Liquid by-products',
    'bois.taille': 'Pruning wood',
    'sarments': 'Vine shoots',
    'rafles': 'Grape stems',
    'lies': 'Wine lees',
    'autre.biomasse': 'Other biomass',
    'ressources.disponibles': 'Available Resources',
    
    // Flow Allocation & Supply Strategy
    'strategie.approvisionnement': 'Supply Strategy',
    'flux.biomasse': 'Biomass Flow',
    'flux.proteges': 'Protected Flows',
    'flux.negociables': 'Negotiable Flows',
    'flux.disponibles': 'Available Flows',
    'allocation.conservative': 'Conservative Base',
    'potentiel.negociable': 'Negotiable Potential',
    'disponibilite.immediate': 'Immediate Availability',
    
    // Infrastructure
    'infrastructure.title': 'Existing Infrastructure',
    'infrastructure.subtitle': 'Valorization facilities in place',
    'infrastructure.distilleries': 'Distilleries',
    'infrastructure.methanisation': 'Methanization Sites',
    'infrastructure.compostage': 'Composting Facilities',
    'infrastructure.biomasse': 'Biomass Plants',
    'infrastructure.total': 'Total facilities',
    'infrastructure.co2.evite': 'Annual CO₂ avoided',
    'infrastructure.capacite': 'Existing capacity',
    
    // Seasonal & Timeline
    'disponibilite.saisonniere': 'Seasonal Availability',
    'calendrier.recolte': 'Harvest Calendar',
    'planning': 'Planning',
    'maintenance': 'Maintenance',
    'formation': 'Training',
    'vendanges': 'Harvest',
    'taille': 'Pruning',
    'recolte': 'Collection',
    'vue.lineaire': 'Linear View',
    'vue.circulaire': 'Circular View',
    'legende.intensite': 'Intensity Legend',
    'intensite.peak': 'Peak',
    'intensite.eleve': 'High',
    'intensite.moyen': 'Medium',
    'intensite.faible': 'Low',
    
    // Months
    'mois.janvier': 'January',
    'mois.fevrier': 'February',
    'mois.mars': 'March',
    'mois.avril': 'April',
    'mois.mai': 'May',
    'mois.juin': 'June',
    'mois.juillet': 'July',
    'mois.aout': 'August',
    'mois.septembre': 'September',
    'mois.octobre': 'October',
    'mois.novembre': 'November',
    'mois.decembre': 'December',
    
    // Valorization Methods
    'valorisation.title': 'Valorization Methods',
    'valorisation.distillation': 'Distillation',
    'valorisation.compostage': 'Composting',
    'valorisation.methanisation': 'Methanization',
    'valorisation.epandage': 'Spreading',
    'valorisation.saf': 'Sustainable Aviation Fuel',
    'valorisation.distillation.desc': 'Transformation into alcohol and spirits',
    'valorisation.compostage.desc': 'Production of organic amendments',
    'valorisation.methanisation.desc': 'Production of biogas and digestate',
    'valorisation.epandage.desc': 'Direct soil amendment',
    'valorisation.saf.desc': 'Aviation biofuel production',
    'valorisation.chaines.etablies': 'Established valorization chains',
    'valorisation.opportunite.saf': 'SAF opportunity (30%)',
    'valorisation.conformite': 'EU waste directive compliance',
    'valorisation.impact.economique': 'Regional economic impact',
    'valorisation.emplois.crees': 'Jobs created',
    'valorisation.contexte.regional': 'Regional context',
    'valorisation.methodologie': 'Methodology based on 2023 sectoral data',
    
    // Industry News & Players
    'actualites.secteur': 'Industry News',
    'acteurs.industriels': 'Industry Players',
    'entreprise.bioenergie': 'Advanced Bioenergy',
    'entreprise.bioenergie.desc': 'Production of 2nd generation biofuels from viticulture waste',
    'entreprise.valorisation': 'Green Valorization',
    'entreprise.valorisation.desc': 'Specialist in treatment and valorization of agricultural by-products',
    'entreprise.innovation': 'SAF Innovation',
    'entreprise.innovation.desc': 'Development of biomass-to-fuel conversion technologies',
    'statut.certifie': 'Certified',
    'statut.en.cours': 'In progress',
    'statut.planifie': 'Planned',
    'feedstock': 'Feedstock',
    'certification': 'Certification',
    'biomass.to.liquids': 'Biomass-to-liquids',
    'partenariat.recherche': 'Research partnership',
    'projet.demonstration': 'Demonstration project',
    'investissement.prevu': 'Planned investment',
    'emplois.potentiels': 'Potential jobs',
    'debut.production': 'Production start',
    
    // Economic Terms
    'cout.tonne': 'Cost per tonne',
    'prix.marche': 'Market price',
    'retour.investissement': 'Return on investment',
    'benefice.annuel': 'Annual profit',
    'cout.transport': 'Transport cost',
    'cout.transformation': 'Processing cost',
    'revenus.potentiels': 'Potential revenue',
    'marge.beneficiaire': 'Profit margin',
    
    // Partnerships & Collaboration - COMPLETE UPDATE
    'opportunites.partenariat': 'Partnership Opportunities',
    'collaboration.recherche': 'Research Collaboration',
    'financement.disponible': 'Available Funding',
    'subventions.europeennes': 'European Grants',
    'aides.regionales': 'Regional Aid',
    
    // Core Partnership Keys - UPDATED
    'partnerships.title': 'Strategic Partnerships',
    'partnerships.subtitle': 'Collaborative ecosystem for valorizing viticulture waste into sustainable aviation fuel',
    'partnerships.strategic.partnerships': 'Strategic Partnerships',
    'partnerships.header.subtitle': 'Collaborative ecosystem for valorization of viticulture waste into sustainable aviation fuel in the region',
    'partnerships.opportunities.title': 'Partnership Opportunities',
    'partnerships.collaborative.ecosystem': 'Collaborative ecosystem for SAF development',
    'partnerships.note.title': 'Note',
    'partnerships.framework.note': 'This analysis is based on feedback from Neste (Finland), BP Bunge (Brazil) and Total Energies (France) projects',
    'partnerships.types.needed': 'Partnership Types',
    'partnerships.main.types': 'Main types',
    'partnerships.target.partners': 'Target Partners',
    'partnerships.network.objective': 'Network objective',
    'partnerships.cost.reduction': 'Cost Reduction',
    'partnerships.waste.treatment': 'Waste treatment',
    'partnerships.new.revenues': 'New Revenues',
    'partnerships.annual.potential': 'Annual potential',
    'partnerships.waste.to.revenue': 'Transform waste costs into revenue streams',
    
    // Partnership Categories - COMPLETE UPDATE
    'partnerships.collectivites.title': 'Local Authorities',
    'partnerships.collectivites.desc': 'Partnerships with local authorities for coordinated waste management',
    'partnerships.producers.title': 'Wine Producers',
    'partnerships.waste.available': 'waste available',
    'partnerships.producers.desc': 'Partnership with wine producers to secure viticulture waste supply',
    'partnerships.industrial.title': 'Industrial Partners',
    'partnerships.industrial.desc': 'Companies with existing processing infrastructure',
    'partnerships.institutional.title': 'Institutional Partners',
    'partnerships.institutional.desc': 'Public organizations and research centers',
    'partnerships.saf.companies.title': 'SAF Companies',
    'partnerships.feedstock.demand': 'Growing demand for feedstock',
    'partnerships.saf.companies.desc': 'Collaboration with sustainable aviation fuel producers to meet growing demand',
    'partnerships.tourism.title': 'Tourism Operators',
    'partnerships.sustainability.story': 'Sustainability storytelling',
    'partnerships.tourism.desc': 'Sustainable image valorization with tourism operators and airlines',
    'partnerships.regional.government.title': 'Regional Government',
    'partnerships.circular.economy': 'Circular economy support',
    'partnerships.regional.government.desc': 'Public support to develop circular economy and sustainable sectors',
    
    // Benefits - COMPLETE UPDATE
    'partnerships.benefits.waste.reduction': 'Waste reduction',
    'partnerships.benefits.local.revenue': 'Local revenue',
    'partnerships.benefits.job.creation': 'Job creation',
    'partnerships.benefits.carbon.goals': 'Carbon goals',
    'partnerships.benefits.waste.valorization': 'Waste valorization',
    'partnerships.benefits.additional.income': 'Additional income',
    'partnerships.benefits.sustainability': 'Sustainability',
    'partnerships.benefits.cost.reduction': 'Cost reduction',
    'partnerships.benefits.existing.infrastructure': 'Existing infrastructure',
    'partnerships.benefits.optimized.logistics': 'Optimized logistics',
    'partnerships.benefits.technical.expertise': 'Technical expertise',
    'partnerships.benefits.economies.scale': 'Economies of scale',
    'partnerships.benefits.regulatory.support': 'Regulatory support',
    'partnerships.benefits.financement.public': 'Public funding',
    'partnerships.benefits.validation.scientifique': 'Scientific validation',
    'partnerships.benefits.reseau.institutionnel': 'Institutional network',
    'partnerships.benefits.waste.elimination': 'Waste elimination',
    'partnerships.benefits.additional.revenue': 'Additional revenue',
    'partnerships.benefits.sustainable.image': 'Sustainable image',
    'partnerships.benefits.secure.feedstock': 'Secure feedstock',
    'partnerships.benefits.production.scale': 'Production scaling',
    'partnerships.benefits.regulatory.compliance': 'Regulatory compliance',
    'partnerships.benefits.green.branding': 'Green branding',
    'partnerships.benefits.customer.engagement': 'Customer engagement',
    'partnerships.benefits.marketing.differentiation': 'Marketing differentiation',
    
    // Industry Examples & Table - COMPLETE UPDATE
    'partnerships.neste.model': 'Neste Model',
    'partnerships.neste.desc': 'Decentralized partnerships with local collectors',
    'partnerships.bp.model': 'BP Bunge Model',
    'partnerships.bp.desc': 'Vertical integration with agricultural producers',
    'partnerships.total.model': 'Total Energies Model',
    'partnerships.total.desc': 'Multi-partner collaborative approach',
    'partnerships.feedstock.food.waste': 'Food waste',
    'partnerships.feedstock.agricultural.residues': 'Agricultural residues',
    'partnerships.feedstock.mixed.biomass': 'Mixed biomass',
    'partnerships.tonnes.year': 'tonnes/year',
    'partnerships.tonnes.saf.year': 'tonnes SAF/year',
    'partnerships.table.model': 'Model',
    'partnerships.table.description': 'Description',
    'partnerships.table.partners': 'Partners',
    'partnerships.table.feedstock': 'Feedstock',
    'partnerships.table.capacity': 'Capacity',
    'partnerships.partnership.total': 'Total Energies Partnership',
    'partnerships.ethanol.agricultural.waste': 'Ethanol from agricultural waste',
    'partnerships.certified': 'approved',
    'partnerships.green.fuels': 'Green Fuels',
    'partnerships.mobilized': 'mobilized',
    'partnerships.hydrogen.aircraft.2035': 'Hydrogen aircraft 2035',
    'partnerships.french.airports.equipped': 'French airports equipped',
    'partnerships.saf.strategy.france.2030': 'SAF Strategy France 2030',
    'partnerships.over.5.years': 'over 5 years',
    'partnerships.tonnes.saf.year.capacity': 'tonnes SAF/year capacity',
    'partnerships.biorefineries.modernized': 'biorefineries modernized',
    'partnerships.biomass.suppliers': 'biomass suppliers',
    'partnerships.investment': 'Investment',
    'partnerships.capacity': 'Capacity',
    'partnerships.technology': 'Technology',
    'partnerships.partnership': 'Partnership',
    
    // Implementation & Phases - COMPLETE
    'partnerships.progressive.approach': 'Progressive approach based on sectoral best practices',
    'partnerships.phase': 'Phase',
    'partnerships.duration': 'Duration',
    'partnerships.partners': 'Partners',
    'partnerships.target.volume': 'Target volume',
    'partnerships.tonnes': 'tonnes',
    
    // Existing Phase Keys
    'partnerships.phase.pilot': 'Pilot Phase',
    'partnerships.phase.pilot.desc': 'Technical and economic validation',
    'partnerships.phase.scale': 'Scale-up Phase',
    'partnerships.phase.scale.desc': 'Progressive scaling',
    'partnerships.phase.mature': 'Mature Phase',
    'partnerships.phase.mature.desc': 'Optimization and regional expansion',
    
    // Value Proposition & Final - COMPLETE
    'partnerships.transform.costs.to.revenue': 'Transform waste costs into revenue streams',
    'partnerships.per.tonne': 'per tonne',
    'partnerships.implementation.planning': 'Implementation Planning',
    'partnerships.roadmap.key.steps': 'Roadmap and key project steps',
    'partnerships.methodology.title': 'Methodology',
    'partnerships.methodology.note': 'Methodology Note',
    'partnerships.strategic.regional.saf': 'Strategic partnerships for regional SAF supply chain',
    
    // Existing Partnership Keys
    'partnerships.value.proposition': 'Value Proposition',
    'partnerships.current.costs': 'Current Costs',
    'partnerships.waste.disposal': 'Waste disposal',
    'partnerships.transport.costs': 'Transport costs',
    'partnerships.saf.revenue': 'SAF revenue',
    'partnerships.carbon.credits': 'Carbon credits',
    'partnerships.net.benefit': 'Net benefit',
    'partnerships.implementation.phases': 'Implementation Phases',
    'partnerships.industry.examples': 'Industry Examples',
    'partnerships.examples.subtitle': 'Partnership models observed in the industry',
    'partnerships.framework.disclaimer': 'Analysis framework based on sectoral data',
    'timeline.months': 'months',
    
    // Legacy Partnership Keys
    'partenariats.requis': 'Required Partnership Types',
    'types.principaux': 'Main types',
    'partenaires.cibles': 'Target Partners',
    'objectif.reseau': 'Network objective',
    'reduction.couts': 'Cost Reduction',
    'traitement.dechets': 'Waste treatment',
    'nouveaux.revenus': 'New Revenues',
    'potentiel.annuel': 'Annual potential',
    'phases.implementation': 'Implementation Phases',
    'approche.progressive': 'Progressive approach based on sector best practices',
    'duree': 'Duration',
    'partenaires': 'Partners',
    'volume.cible': 'Target volume',
    'proposition.valeur': 'Value Proposition',
    'transformation.couts': 'Transform waste costs into revenue streams',
    'benefice.net.tonne': 'Net benefit per tonne',
    'planification.oeuvre': 'Implementation Planning',
    'roadmap.etapes': 'Project roadmap and key stages',
    'timeline.implementation': 'Implementation Timeline',
    
    // Project Phases
    'etude.faisabilite': 'Feasibility Study',
    'developpement.partenariats': 'Partnership Development',
    'financement.autorisations': 'Financing and Permits',
    'construction.infrastructure': 'Infrastructure Construction',
    'demarrage.production': 'Production Startup',
    'expansion.regionale': 'Regional Expansion',
    
    // Phase Status
    'termine': 'Completed',
    'en.cours': 'In progress',
    'planifie': 'Planned',
    'progression': 'Progress',
    'jalons': 'Milestones',
    
    // Phase Details
    'analyse.complete': 'Complete technical and economic project analysis',
    'etude.marche': 'Market study',
    'analyse.technique': 'Technical analysis',
    'modele.economique': 'Economic model',
    'rapport.final': 'Final report',
    
    // Stakeholders
    'parties.prenantes': 'Stakeholders',
    'equipe.projet': 'Project team',
    'consultants.externes': 'External consultants',
    'investisseurs': 'Investors',
    'dependances': 'Dependencies',
    'aucune.dependance': 'No dependencies',
    'risques.identifies': 'Identified Risks',
    'delais.consultants': 'Consultant delays',
    'evolution.reglementaire': 'Regulatory evolution',
    
    // Project Summary
    'resume.global.projet': 'Global Project Summary',
    'phases.terminees': 'Completed phases',
    'phases.en.cours': 'Phases in progress',
    'progression.totale': 'Total progress',
    'mois.estimes': 'Estimated months',
    
    // Methodology & Data
    'methodologie.title': 'Methodology',
    'sources.donnees': 'Data Sources',
    'collecte.donnees': 'Data Collection',
    'validation.donnees': 'Data Validation',
    'mise.jour.donnees': 'Data updates',
    'references.scientifiques': 'Scientific References',
    'hypotheses.calcul': 'Calculation Assumptions',
    'limites.etude': 'Study Limitations',
    
    // Contact & Support
    'contact.title': 'Contact',
    'support.technique': 'Technical Support',
    'informations.projet': 'Project Information',
    'demande.donnees': 'Data Request',
    'collaboration.industrie': 'Industry Collaboration',
    
    // Debug & System
    'debug.mode': 'Debug Mode',
    'debug.donnees.region': 'Region data',
    'debug.traductions.manquantes': 'Missing translations',
    'debug.validation.donnees': 'Data validation',
    'erreur.chargement': 'Loading error',
    'donnees.non.disponibles': 'Data not available',
    
    // Units & Measurements - COMPLETE WITH ALL UNIT KEYS
    'unite.tonnes': 'tonnes',
    'unite.hectares': 'ha',
    'unite.pourcentage': '%',
    'unite.euros': '€',
    'unite.emplois': 'jobs',
    'unite.annee': '/year',
    'unite.kilogrammes': 'kg',
    'unite.litres': 'L',
    'units.tonne': 'tonne',
    'units.tonnes': 'tonnes',
    'litres.an': 'litres/year',
    
    // Cost-Benefit Analysis & Economic Projections Units
    'currency.euro': '€',
    'units.million': 'M',
    'units.kilotonnes': 'kt',
    'units.kilo': 'k',
    'units.percent': '%',
    'common.plus': '+',
    'common.year': 'year',
    'units.kilograms': 'kg',
    'units.liters': 'L',
    'units.liter': 'L',
    'units.tonnes': 't',
    'units.tonne': 't',
    
    // Resources Tab - COST BENEFIT ANALYSIS (NEW KEYS)
    'cost.benefit.title': 'Cost-Benefit Analysis',
    'cost.benefit.comparison': 'Comparison',
    'cost.benefit.timeline': 'Timeline',
    'cost.benefit.breakdown': 'Breakdown',
    'cost.benefit.profit.improvement': 'Profit improvement',
    'cost.benefit.additional.benefit': 'Additional benefit',
    'cost.benefit.jobs.created': 'Jobs created',
    'cost.benefit.co2.avoided.annual': 'Annual CO₂ avoided',
    'cost.benefit.real.data': 'Real Data',
    'cost.benefit.revenue': 'Revenue',
    'cost.benefit.operating.costs': 'Operating costs',
    'cost.benefit.net.profit': 'Net profit',
    'cost.benefit.traditional.valorization': 'Traditional valorization',
    'cost.benefit.saf.valorization': 'SAF valorization',
    'cost.benefit.detailed.comparison': 'Detailed Comparison',
    'cost.benefit.category': 'Category',
    'cost.benefit.traditional': 'Traditional',
    'cost.benefit.saf': 'SAF',
    'cost.benefit.difference': 'Difference',
    'cost.benefit.improvement': 'Improvement',
    'cost.benefit.context': 'Context',
    'cost.benefit.languedoc.context': 'Analysis based on industrial capacities and established logistics infrastructure of France\'s largest wine region',
    
    // Economy Tab - FINANCING OVERVIEW (NEW KEYS)
    'economy.financing.overview': 'Financing Overview',
    'economy.equity.funding': 'Equity Funding',
    'economy.equity.percentage': '35% equity',
    'economy.bank.debt': 'Bank Debt',
    'economy.interest.rate': '4.5% interest rate',
    'economy.subsidies': 'Subsidies',
    'economy.eu.france.funding': 'EU + France 2030',
    'economy.total.investment': 'Total Investment',
    'economy.capacity.description': '80kt SAF capacity',
    'economy.scaling.note': 'Scalable modeling based on regional biomass availability',
    
    // Common Actions
    'voir.details': 'View details',
    'telecharger': 'Download',
    'exporter.donnees': 'Export data',
    'imprimer.rapport': 'Print report',
    'partager.lien': 'Share link',
    'copier.lien': 'Copy link',
    'fermer': 'Close',
    'ouvrir': 'Open',
    'suivant': 'Next',
    'precedent': 'Previous',
    'retour': 'Back',
    'accueil': 'Home'
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');
  const [debugMode, setDebugMode] = useState(false);
  const [missingTranslations, setMissingTranslations] = useState<string[]>([]);

  const t = (key: string, params?: Record<string, string>): string => {
    let translation = translations[language][key];
    
    // Track missing translations in debug mode
    if (!translation && debugMode) {
      if (!missingTranslations.includes(key)) {
        setMissingTranslations(prev => [...prev, key]);
        console.warn(`Missing translation: ${key}`);
      }
      return `[MISSING: ${key}]`;
    }
    
    // Fallback to key if translation not found
    if (!translation) {
      translation = key;
    }
    
    // Handle parameter replacement like {region}, {years}, {tonnage}, etc.
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param]);
      });
    }
    
    return translation;
  };

  const getMissingTranslations = (): string[] => {
    return [...missingTranslations];
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      setLanguage, 
      t, 
      debugMode, 
      setDebugMode,
      getMissingTranslations 
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
